// Example dartified, see original for reference:
// https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c
// Run it: dart run textures_raw_data.dart
// WARNING: expects resources from the raylib source
import 'dart:ffi';
import '../../base.dart';

const int screenWidth = 800;
const int screenHeight = 450;

void main()
{
  final rl = findRaylib('raylib-5.5_linux_amd64/lib');

  rl.Core.InitWindow(screenWidth, screenHeight, "textures_raw_data".toC);
  rl.Core.SetWindowMonitor(0);
  rl.Core.SetTargetFPS(60);

  final fudesumiRaw = rl.Core.LoadImageRaw(
    "../resources/fudesumi.raw".toC,
    384, 512, PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8.value, 0
  );
  final fudesumi = rl.Core.LoadTextureFromImage(fudesumiRaw);
  rl.Core.UnloadImage(fudesumiRaw);

  int width = 960;
  int height = 480;

  // NOTE: Color$.Raw, because it is freed on raylib side on `UnloadImage`
  final pixels = rl.Temp.Color$.Raw(width*height);

  for (int y = 0; y < height; y++)
  {
    for (int x = 0; x < width; x++)
    {
      if (((x~/32+y~/32)/1)%2 == 0) pixels[y*width + x] = rl.Color.ORANGE;
      else pixels[y*width + x] = rl.Color.GOLD;
    }
  }

  final checkedIm = rl.Temp.Image$.At('checkedIm');
  checkedIm.ref.data = pixels.cast();
  checkedIm.ref.width = width;
  checkedIm.ref.height = height;
  checkedIm.ref.format = PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8.value;
  checkedIm.ref.mipmaps = 1;

  final checked = rl.Core.LoadTextureFromImage(checkedIm.ref);
  
  rl.Core.UnloadImage(checkedIm.ref);

  while (!rl.Core.WindowShouldClose())
  {
    rl.Core.BeginDrawing();

      rl.Core.ClearBackground(rl.Color.RAYWHITE);

      rl.Core.DrawTexture(
        checked,
        (screenWidth/2 - checked.width/2).toInt(),
        (screenHeight/2 - checked.height/2).toInt(),
        rl.Core.Fade(rl.Color.WHITE, 0.5)
      );
      
      rl.Core.DrawTexture(fudesumi, 430, -30, rl.Color.WHITE);

      rl.Core.DrawText(
        "CHECKED TEXTURE ".toC,
        84, 85, 30, rl.Color.BROWN
      );
      rl.Core.DrawText(
        "GENERATED by CODE".toC,
        72, 148, 30, rl.Color.BROWN
      );
      rl.Core.DrawText(
        "and RAW IMAGE LOADING".toC,
        46, 210, 30, rl.Color.BROWN
      );

      rl.Core.DrawText(
        "(c) Fudesumi sprite by Eiden Marsal".toC,
        310, screenHeight - 20, 10, rl.Color.BROWN
      );

    rl.Core.EndDrawing();
  }

  rl.Core.UnloadTexture(fudesumi);
  rl.Core.UnloadTexture(checked);

  rl.CloseWindowAndDispose();
}