// Example dartified, see original for reference:
// https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c
// Run it: dart run textures_raw_data.dart
// WARNING: expects resources from the raylib source
import 'dart:ffi';
import '../../base_c.dart';

const int screenWidth = 800;
const int screenHeight = 450;

void main()
{
  findRaylib('raylib-6.0_linux_amd64/lib');

  InitWindow(screenWidth, screenHeight, "textures_raw_data".toC);
  SetTargetFPS(60);

  final fudesumiRaw = LoadImageRaw(
    "../resources/fudesumi.raw".toC,
    384, 512, PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8.value, 0
  );
  final fudesumi = LoadTextureFromImage(fudesumiRaw);
  UnloadImage(fudesumiRaw);

  int width = 960;
  int height = 480;

  // NOTE: Color$.Raw, because it is freed on raylib side on `UnloadImage`
  final pixels = Color$.Raw(width*height);

  for (int y = 0; y < height; y++)
  {
    for (int x = 0; x < width; x++)
    {
      if (((x~/32+y~/32)/1)%2 == 0) pixels[y*width + x] = ORANGE;
      else pixels[y*width + x] = GOLD;
    }
  }

  final checkedIm = Image$.At('checkedIm');
  checkedIm.ref.data = pixels.cast();
  checkedIm.ref.width = width;
  checkedIm.ref.height = height;
  checkedIm.ref.format = PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8.value;
  checkedIm.ref.mipmaps = 1;

  final checked = LoadTextureFromImage(checkedIm.ref);
  
  UnloadImage(checkedIm.ref);

  while (!WindowShouldClose())
  {
    BeginDrawing();

      ClearBackground(RAYWHITE);

      DrawTexture(
        checked,
        (screenWidth/2 - checked.width/2).toInt(),
        (screenHeight/2 - checked.height/2).toInt(),
        Fade(WHITE, 0.5)
      );
      
      DrawTexture(fudesumi, 430, -30, WHITE);

      DrawText(
        "CHECKED TEXTURE ".toC,
        84, 85, 30, BROWN
      );
      DrawText(
        "GENERATED by CODE".toC,
        72, 148, 30, BROWN
      );
      DrawText(
        "and RAW IMAGE LOADING".toC,
        46, 210, 30, BROWN
      );

      DrawText(
        "(c) Fudesumi sprite by Eiden Marsal".toC,
        310, screenHeight - 20, 10, BROWN
      );

    EndDrawing();
  }

  UnloadTexture(fudesumi);
  UnloadTexture(checked);

  CloseWindowAndDispose();
}