name: raylib_dartified
description: Dart-native Raylib bindings that don't make you feel like you're writing C.
version: 5.5.4
repository: https://github.com/TheNoiselessNoise/raylib_dartified

environment:
  sdk: ^3.10.7

dependencies:
  ffi: ^2.2.0
  meta: ^1.17.0
  logging: ^1.3.0
  path: ^1.9.1
  raylib_dartified_base: '>=5.5.0 <6.0.0'

dev_dependencies:
  lints: ^6.0.0