// ignore_for_file: unused_element
// ignore_for_file: curly_braces_in_flow_control_structures
// ignore_for_file: avoid_function_literals_in_foreach_calls
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: type_argument_not_matching_bounds

import 'dart:ffi';
import 'dart:convert';
import 'dart:typed_data';
import 'package:ffi/ffi.dart';
import 'package:raylib_dartified/raylib.dart';

// /*{{SPLIT}}*/part of '../raylib.dart';

/*
  This file is automatically generated!
  Do not modify it directly!

  Modify the template: `utils/templates/temp.dart`
  Generated using: `utils/generators/temp.dart`

  =============================================
  ====== PRE-ALLOCATED MEMORY STATISTICS ======
  =============================================
   IMMUTABLES: 180 Bytes
    REUSABLES: 224 Bytes
  =============================================
             : 404 Bytes
*/

class RaylibTempOptions {
  final int stringCount;

  const RaylibTempOptions({
    this.stringCount = 4,
  });
}

/// A slot-based temporary memory allocator for a single native type [C].
///
/// Manages a named collection of `Pointer<C>` slots identified by string keys.
/// Each slot owns its allocation; slots are freed either manually via [Free]
/// or automatically when [_dispose] is called.
///
/// Subclasses specialise this for literal values, structs, strings, etc.
abstract class RTempAlloc<C extends NativeType> {

  /// The parent [RaylibTemp] context that owns this allocator.
  final RaylibTemp temp;
  
  /// Human-readable name for this allocator, used in debug/log messages.
  final String name;
  
  /// Low-level allocation function. Called with an element [count] and
  /// returns a freshly allocated `Pointer<C>`.
  final Pointer<C> Function([int count]) allocatorFunc;
  
  /// Debug printer: converts a `Pointer<C>` to a human-readable string.
  final String Function(Pointer<C> ptr) printerFunc;

  RTempAlloc(this.temp, this.name, {
    required this.allocatorFunc,
    required this.printerFunc,
  });

  final Map<String, (Pointer<C>, int)> _Slots = {};

  /// Returns a string that identifies the concrete type of this allocator,
  /// including its type parameters.
  String signature() => runtimeType.toString();

  /// Returns the canonical slot key for [key], falling back to `'default'`
  /// when [key] is `null`.
  String slotKey([String? key]) => key ?? 'default';

  String uniqueSlotKey(String key) => '${temp.nextId()}_$key';

  /// Returns the `Pointer<C>` stored in [key], allocating (or reallocating)
  /// if necessary.
  ///
  /// If the slot already exists and its current capacity is >= [count], the
  /// existing pointer is reused. If capacity is insufficient the old block is
  /// freed and a new one of size [count] is allocated.
  ///
  /// [key]   – slot identifier (must not be null).
  /// [count] – minimum element capacity required (default: 1).
  Pointer<C> At(String key, [int count = 1]) {
    final existing = _Slots[key];
    if (existing != null) {
      final (ptr, currentCount) = existing;

      if (count <= currentCount) {
        // temp.logInfo('[TEMP] Reusing slot for $T at $key with $count');
        _Slots[key] = (ptr, count);
        return ptr;
      }
      
      calloc.free(ptr);
    }
    // temp.logInfo('[TEMP] Creating slot for $T at $key with $count');
    final ptr = allocatorFunc(count);
    _Slots[key] = (ptr, count);
    return ptr;
  }

  /// Allocates (or reuses) a slot identified by a unique [key] suffix.
  ///
  /// Behaves like [At], but prepends a monotonic ID from [RaylibTemp.nextId] to
  /// [key], ensuring the slot is never accidentally shared with an unrelated
  /// call that happens to use the same base key.
  ///
  /// Useful when the same allocation site may be called multiple times within
  /// a single scope and each call must get its own independent buffer.
  Pointer<C> AtUnique(String key, [int count = 1]) => At(uniqueSlotKey(key), count);

  /// Returns the pointer stored under [key], or `null` if the slot does not
  /// exist. Does **not** allocate.
  Pointer<C>? Slot(String key) => _Slots[slotKey(key)]?.$1;

  /// Returns `true` if a slot with the given [key] exists.
  bool Has(String key) => _Slots.containsKey(slotKey(key));

  /// Frees the native memory owned by slot [key] and removes it from the
  /// table.
  ///
  /// Throws if [key] has not been allocated.
  void Free(String key) {
    if (!_Slots.containsKey(key)) {
      throw StateError('[FREE] Cannot free unallocated slot $key');
    }
    calloc.free(_Slots[key]!.$1);
    _Slots.remove(key);
  }

  /// Removes the slot entry for [key] from the table **without** freeing the
  /// underlying memory.
  ///
  /// Use when ownership of the pointer has been transferred elsewhere.
  void Unslot(String key) => _Slots.remove(slotKey(key));

  /// Frees all currently tracked slots and clears the slot table.
  ///
  /// Called automatically by the owning [RaylibTemp] during disposal.
  void _dispose() {
    if (_Slots.isNotEmpty) {
      temp.debugFreeInfo('Freeing user-defined ${_Slots.length} $name slots');
      _Slots.entries.forEach((x) {
        temp.debugFreeInfo('[FREE] ${x.key}');
        calloc.free(x.value.$1);
      });
      _Slots.clear();
    }
  }
}

/// A [RTempAlloc] that also knows how to write Dart values of type [X] into
/// native [C] memory, and supports typed-list array operations.
///
/// [X] is the Dart-side value type (e.g. `int`, `double`).
/// [C] is the corresponding [NativeType] (e.g. `Int32`, `Float`).
class RTempLitAlloc<X, C extends NativeType> extends RTempAlloc<C> {
  
  /// Casts an untyped [Pointer] to `Pointer<C>`.
  Pointer<C> Function(Pointer ptr) castFunc;
  
  /// Returns the size in bytes of a single [C] element.
  int Function() sizeOfFunc;
  
  /// Writes a single Dart value [value] into the memory pointed to by [ptr].
  void Function(Pointer<C> ptr, X value) literalSetterFunc;
  
  /// Writes [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<C> ptr, int i, X value) indexSetterFunc;

  RTempLitAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.castFunc,
    required this.sizeOfFunc,
    required this.literalSetterFunc,
    required this.indexSetterFunc,
  });
  
  /// Returns the total byte size for [count] elements.
  int Size([int count = 1]) => count*sizeOfFunc();

  /// Allocates a fresh (unslotted) block of [count] elements and returns it.
  ///
  /// The caller is responsible for freeing this pointer.
  Pointer<C> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted array.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> RawArray(List<X> array) => Raw(array.length);

  /// Allocates an unslotted array and populates it from [array].
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> RawArrayPopulated(List<X> array) {
    final p = Raw(array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, array[i]);
    return p;
  }

  /// Returns the pointer for the slot identified by [key] (default: `'default'`),
  /// writing [value] into it when provided.
  ///
  /// Allocates the slot on first use.
  Pointer<C> Value([X? value, String? key]) {
    final p = At(slotKey(key));
    if (value != null) literalSetterFunc(p, value);
    return p;
  }

  /// Writes [array] into a slot of sufficient capacity and returns the pointer.
  ///
  /// [key] defaults to `'default'`. The slot is grown automatically if the
  /// current capacity is smaller than `array.length`.
  Pointer<C> Array(List<X> array, {String? key}) {
    final p = At(slotKey(key), array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, array[i]);
    return p;
  }

  /// Allocates (or reuses) a slot of [count] elements, populating each index
  /// [i] with the value returned by `init(i)`.
  Pointer<C> Fill(int count, X Function(int) init, {String? key}) {
    final p = At(slotKey(key), count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(i));
    return p;
  }

  /// Writes [o] into slot `'1'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '1')`. Use [RefOrNull1] if [o] may be `null`
  /// and the callee expects [nullptr] in that case.
  Pointer<C> Ref1([X? o]) => Value(o, '1');

  /// Writes [o] into slot `'2'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '2')`. Use [RefOrNull2] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<C> Ref2([X? o]) => Value(o, '2');

  /// Writes [o] into slot `'3'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '3')`. Use [RefOrNull3] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<C> Ref3([X? o]) => Value(o, '3');

  /// Writes [o] into slot `'4'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '4')`. Use [RefOrNull4] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<C> Ref4([X? o]) => Value(o, '4');

  /// Writes [o] into slot `'1'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref1] when the C API uses a null pointer to signal "no value".
  Pointer<C> RefOrNull1(X? o) => o == null ? nullptr : Ref1(o);

  /// Writes [o] into slot `'2'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref2] when the C API uses a null pointer to signal "no value".
  Pointer<C> RefOrNull2(X? o) => o == null ? nullptr : Ref2(o);

  /// Writes [o] into slot `'3'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref3] when the C API uses a null pointer to signal "no value".
  Pointer<C> RefOrNull3(X? o) => o == null ? nullptr : Ref3(o);

  /// Writes [o] into slot `'4'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref4] when the C API uses a null pointer to signal "no value".
  Pointer<C> RefOrNull4(X? o) => o == null ? nullptr : Ref4(o);
}

/// Extends [RTempLitAlloc] with typed-list bulk copy support.
///
/// [asTypedList] bridges between the native pointer and a Dart [TypedDataList],
/// enabling zero-copy bulk memory operations.
abstract class RTempLitTypedListAlloc<X, C extends NativeType, L extends TypedDataList> extends RTempLitAlloc<X, C> {

  /// Returns a Dart [List<X>] view of [length] integer elements at [ptr].
  List<int> Function(Pointer<C> ptr, int length) asDartList;

  /// Wraps [ptr] as a Dart [TypedDataList] of [length] elements.
  ///
  /// The list is a **view** into native memory, so mutations are reflected
  /// immediately in the native buffer.
  TypedDataList Function(Pointer<C> ptr, int length) asTypedList;

  /// Wraps a region of [buffer] as a Dart [L] list without copying.
  ///
  /// Acts as the inverse of [asTypedList]: where [asTypedList] views native
  /// memory as a Dart typed list, [fromBuffer] views an existing Dart
  /// [ByteBuffer] as an [L], allowing [FromTypedData] to bulk-copy foreign
  /// typed data into a slot without going through raw bytes.
  ///
  /// [offsetInBytes] and [length] are forwarded directly to the underlying
  /// `buffer.asXxxList()` call, so the usual alignment and bounds rules apply.
  L Function(ByteBuffer buffer, int offsetInBytes, int length) fromBuffer;

  RTempLitTypedListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required this.asDartList,
    required this.asTypedList,
    required this.fromBuffer,
  });

  /// Copies [length] elements from [src] into a slot and returns the pointer.
  ///
  /// Uses [asTypedList] for the bulk copy, which avoids an element-by-element
  /// loop. [key] defaults to `'default'`.
  Pointer<C> Copy(Pointer<C> src, int length, {String? key}) {
    final p = At(slotKey(key), length);
    final srcList = asTypedList(castFunc(src), length);
    asTypedList(castFunc(p), length).setAll(0, srcList);
    return p;
  }

  /// Allocates (or reuses) a slot of [length] elements and returns its pointer,
  /// without writing any data into it.
  ///
  /// Unlike [Array] or [Fill], the contents are left uninitialized, useful when
  /// the buffer will be populated by a C call rather than from Dart.
  /// [key] defaults to `'Sized<C>'`.
  Pointer<C> Sized(int length, {String? key}) => At(key ?? 'Sized$C', length);

  /// Copies [length] elements from a typed list [list] into a slot.
  Pointer<C> FromTypedList(L list, {String? key}) {
    final p = Sized(list.length, key: key);
    asTypedList(castFunc(p), list.length).setAll(0, list);
    return p;
  }

  Pointer<C> FromTypedData(TypedData data, {String? key}) {
    final elemSize = sizeOfFunc();
    final byteCount = data.lengthInBytes;
    assert(byteCount % elemSize == 0);
    final length = byteCount ~/ elemSize;
    final p = Sized(length, key: key);
    final src = fromBuffer(data.buffer, data.offsetInBytes, length);
    asTypedList(castFunc(p), length).setAll(0, src);
    return p;
  }
}

/// A typed-list allocator for integer native types (e.g. `Int32`, `Uint8`).
///
/// Adds byte-serialisation helpers that convert the native integer array to
/// big-endian or little-endian byte lists, useful for hashing and I/O.
class RTempLitTypedIntListAlloc<X, C extends NativeType, L extends TypedDataList> extends RTempLitTypedListAlloc<X, C, L> {

  RTempLitTypedIntListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required super.asDartList,
    required super.asTypedList,
    required super.fromBuffer,
  });

  /// Serialises [length] words starting at [ptr] to a flat big-endian byte list.
  ///
  /// Each word is split into `sizeOf<C>()` bytes, most-significant byte first.
  List<int> ToBEBytes(Pointer<C> ptr, int length) {
    final wordSize = sizeOfFunc();
    return asDartList(ptr, length).expand((word) =>
      .generate(wordSize, (i) => (word >> ((wordSize - 1 - i) * 8)) & 0xFF)
    ).toList();
  }

  /// Serialises [length] words starting at [ptr] to a flat little-endian byte list.
  ///
  /// Each word is split into `sizeOf<C>()` bytes, least-significant byte first.
  List<int> ToLEBytes(Pointer<C> ptr, int length) {
    final wordSize = sizeOfFunc();
    return asDartList(ptr, length).expand((word) =>
      .generate(wordSize, (i) => (word >> (i * 8)) & 0xFF)
    ).toList();
  }
}

/// A typed-list allocator for floating-point native types (e.g. `Float`, `Double`).
class RTempLitTypedFloatListAlloc<X, C extends NativeType, L extends TypedDataList> extends RTempLitTypedListAlloc<X, C, L> {

  RTempLitTypedFloatListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required super.asDartList,
    required super.asTypedList,
    required super.fromBuffer,
  });
}

/// A slot-based allocator for arrays of **pointers** to literal elements.
///
/// Manages `Pointer<Pointer<C>>` slots; each inner pointer is produced by
/// [rawArrayFunc] from a `List<X>`.
class RTempLitPtrAlloc<X, C extends NativeType> extends RTempAlloc<Pointer<C>> {

  /// Converts a flat `List<X>` into an allocated `Pointer<C>` array.
  ///
  /// The caller is responsible for the lifetime of the inner pointers.
  Pointer<C> Function(List<X> array) rawArrayFunc;

  RTempLitPtrAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.rawArrayFunc,
  });

  /// Allocates an unslotted `Pointer<Pointer<C>>` of [count] elements.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<C>> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted pointer-of-pointers from a list of value arrays.
  ///
  /// Each `arrays[i]` is converted via [rawArrayFunc].
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<C>> RawArray(List<List<X>> arrays) {
    final pp = Raw(arrays.length);
    for (int i = 0; i < arrays.length; i++) {
      pp[i] = rawArrayFunc(arrays[i]);
    }
    return pp;
  }

  /// Writes each sub-array in [arrays] into a tracked slot via [rawArrayFunc]
  /// and returns the outer `Pointer<Pointer<C>>`
  Pointer<Pointer<C>> Fill(List<List<X>> arrays, {String? key}) {
    final pp = At(slotKey(key), arrays.length);
    for (int i = 0; i < arrays.length; i++) pp[i] = rawArrayFunc(arrays[i]);
    return pp;
  }

  /// Fills a tracked slot of [count] pointers by calling `init(i)` for each
  /// index and storing the result.
  Pointer<Pointer<C>> FillRaw(int count, Pointer<C> Function(int) init, {String? key}) {
    final pp = At(slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }
}

/// A slot-based allocator for native structs of type [C], accepting Dart-side
/// [StructD] wrappers of type [D].
///
/// Bridges between the ergonomic Dart [StructD] layer and raw `Pointer<C>`
/// memory, supporting both single-value and array slots.
class RTempStructAlloc<C extends Struct, D extends StructD<C, D>> extends RTempAlloc<C> with RaylibTempStructAllocatorBase<RaylibTemp, Pointer<C>, D> {

  /// Casts an untyped [Pointer] to `Pointer<C>`.
  Pointer<C> Function(Pointer ptr) castFunc;

  /// Returns the [C] struct value referenced by [ptr].
  ///
  /// Equivalent to `ptr.ref`, provided as a function because Dart's type system
  /// does not allow calling `.ref` directly on a generic `Pointer<C>`.
  C Function(Pointer<C> ptr) refFunc;

  /// Assigns [value] to the struct referenced by [ptr].
  ///
  /// Equivalent to `ptr.ref = value`, provided as a function for the same
  /// reason as [refFunc]: Dart's type system does not permit assignment
  /// through `.ref` on a generic `Pointer<C>`.
  Pointer<C> Function(Pointer<C> ptr, C value) setRefFunc;

  /// Returns the size in bytes of a single [C] struct.
  int Function() sizeOfFunc;
  
  /// Writes the Dart value [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<C> ptr, int i, D value) writeIntoIndexedFunc;
  
  /// Writes the Dart value [value] into the struct at [ptr].
  void Function(Pointer<C> ptr, D value) writeIntoFunc;
  
  /// Copies the raw C struct [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<C> ptr, int i, C value) setCFunc;
  
  /// Returns the [C] struct at index [i] of the array at [ptr].
  C Function(Pointer<C> ptr, int i) indexerFunc;
  
  /// Overwrites the [i]-th element of the array at [ptr] with [value].
  void Function(Pointer<C> ptr, int i, C value) indexSetterFunc;

  /// Converts a `Pointer<C>` to its Dart-side [D] wrapper, referencing the
  /// memory at that pointer.
  D Function(Pointer<C> ptr) ptrToDFunc;

  RTempStructAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.castFunc,
    required this.refFunc,
    required this.setRefFunc,
    required this.sizeOfFunc,
    required this.writeIntoIndexedFunc,
    required this.writeIntoFunc,
    required this.setCFunc,
    required this.indexerFunc,
    required this.indexSetterFunc,
    required this.ptrToDFunc,
  });

  /// Returns the total byte size for [count] structs.
  int Size([int count = 1]) => count*sizeOfFunc();

  /// Allocates an unslotted block of [count] structs.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted array and writes each [X] value from [array] into it.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> RawArray(List<D> array) {
    final p = Raw(array.length);
    for (int i = 0; i < array.length; i++) writeIntoIndexedFunc(p, i, array[i]);
    return p;
  }

  /// Allocates an unslotted array of [count] structs, populating each via
  /// `init(i, struct)` which writes directly into the native memory.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> RawFillInto(int count, void Function(int, C) init) {
    final p = Raw(count);
    for (int i = 0; i < count; i++) init(i, indexerFunc(p, i));
    return p;
  }

  /// Allocates an unslotted array of [count] structs, setting each element to
  /// the [C] returned by `init(ptr, i)`.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<C> RawFillWith(int count, C Function(Pointer<C>, int) init) {
    final p = Raw(count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(p, i));
    return p;
  }

  /// Copies [length] structs from [src] into a tracked slot using [setCFunc].
  Pointer<C> Copy(Pointer<C> src, int length, {String? key}) {
    final p = At(slotKey(key), length);
    for (int i = 0; i < length; i++) setCFunc(p, i, indexerFunc(src, i));
    return p;
  }

  /// Returns the pointer for slot [key], optionally writing [value] into it.
  ///
  /// Allocates the slot on first use.
  Pointer<C> Value([D? value, String? key]) {
    final p = At(slotKey(key));
    if (value != null) writeIntoFunc(p, value);
    return p;
  }

  /// Writes [array] into a tracked slot of sufficient capacity.
  Pointer<C> Array(List<D> array, {String? key}) {
    final p = At(slotKey(key), array.length);
    for (int i = 0; i < array.length; i++) writeIntoIndexedFunc(p, i, array[i]);
    return p;
  }

  /// Fills a tracked slot of [count] structs, producing each element via
  /// `init(i)` and writing it through [writeIntoIndexedFunc].
  Pointer<C> Fill(int count, D Function(int) init, {String? key}) {
    final p = At(slotKey(key), count);
    for (int i = 0; i < count; i++) writeIntoIndexedFunc(p, i, init(i));
    return p;
  }

  /// Fills a tracked slot of [count] structs by calling `init(i, struct)`
  /// which writes directly into the native struct fields.
  Pointer<C> FillInto(int count, void Function(int, C) init, {String? key}) {
    final p = At(slotKey(key), count);
    for (int i = 0; i < count; i++) init(i, indexerFunc(p, i));
    return p;
  }

  /// Fills a tracked slot of [count] structs by setting each element to the
  /// [C] returned by `init(ptr, i)`.
  Pointer<C> FillWith(int count, C Function(Pointer<C>, int) init, {String? key}) {
    final p = At(slotKey(key), count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(p, i));
    return p;
  }

  /// Returns a `Pointer<C>` for the given [D] value, using [nullptr] when [x] is `null`.
  ///
  /// Allocates into a numbered slot (1–8) via the corresponding [ToC] call,
  /// so the lifetime is tied to the owning [RaylibTemp].
  Pointer<C> _Ref(D? x, String key) => x == null ? nullptr : PointerTo(x, key);

  /// Allocates [o] into slot `'1'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate1] if the callee may write back into the pointer.
  Pointer<C> Ref1([D? o]) => _Ref(o, '1');

  /// Allocates [o] into slot `'2'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate2] if the callee may write back into the pointer.
  Pointer<C> Ref2([D? o]) => _Ref(o, '2');

  /// Allocates [o] into slot `'3'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate3] if the callee may write back into the pointer.
  Pointer<C> Ref3([D? o]) => _Ref(o, '3');

  /// Allocates [o] into slot `'4'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate4] if the callee may write back into the pointer.
  Pointer<C> Ref4([D? o]) => _Ref(o, '4');

  /// Allocates [o] into slot `'5'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate5] if the callee may write back into the pointer.
  Pointer<C> Ref5([D? o]) => _Ref(o, '5');

  /// Allocates [o] into slot `'6'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate6] if the callee may write back into the pointer.
  Pointer<C> Ref6([D? o]) => _Ref(o, '6');

  /// Allocates [o] into slot `'7'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate7] if the callee may write back into the pointer.
  Pointer<C> Ref7([D? o]) => _Ref(o, '7');

  /// Allocates [o] into slot `'8'`, or returns [nullptr] if [o] is `null`.
  ///
  /// Intended as a short-lived scratch reference within a single C call.
  /// Use [RefUpdate8] if the callee may write back into the pointer.
  Pointer<C> Ref8([D? o]) => _Ref(o, '8');

  /// Allocates [o] into a numbered slot, invokes [fn] with the resulting
  /// pointer, then syncs any mutations back from native memory into [o] via
  /// [setCFunc].
  ///
  /// If [o] is `null`, passes [nullptr] to [fn] and skips the sync step.
  /// This is the foundation for the [RefUpdate1]–[RefUpdate8] helpers, covering
  /// the common pattern of passing a mutable struct pointer to a C function that
  /// may write into it.
  V _RefUpdate<V>(
    D? o,
    V Function(Pointer<C> p) fn,
    Pointer<C> Function(D) alloc,
  ) {
    final p = o != null ? alloc(o) : nullptr;
    final result = fn(p);
    if (o != null) o.setC(refFunc(p));
    return result;
  }

  /// Allocates [o] into slot `'1'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref1] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate1<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref1);

  /// Allocates [o] into slot `'2'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref2] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate2<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref2);

  /// Allocates [o] into slot `'3'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref3] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate3<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref3);

  /// Allocates [o] into slot `'4'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref4] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate4<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref4);

  /// Allocates [o] into slot `'5'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref5] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate5<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref5);

  /// Allocates [o] into slot `'6'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref6] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate6<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref6);

  /// Allocates [o] into slot `'7'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref7] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate7<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref7);

  /// Allocates [o] into slot `'8'`, calls [fn] with the pointer, then
  /// syncs native memory back into [o] via [setCFunc].
  ///
  /// Use this instead of [Ref8] when the C function writes into the struct and
  /// you want the mutations reflected in [o] after the call.
  V RefUpdate8<V>(D? o, V Function(Pointer<C> p) fn) => _RefUpdate(o, fn, Ref8);

  /// Copies the native struct [o] into a uniquely-keyed tracked slot and
  /// returns its Dart-side [X] wrapper via [ptrToDFunc].
  ///
  /// Unique key of the form `'<id>_<key>'` is generated from the allocator's
  /// ID counter. The returned [X] holds a live reference into temp-managed
  /// memory.
  D RefCapture(String key, C o) => ptrToDFunc(setRefFunc(AtUnique(key), o));
}

/// A slot-based allocator for arrays of **pointers** to native structs of type [C].
///
/// Manages `Pointer<Pointer<C>>` slots where each inner `Pointer<C>` is
/// produced from a `List<D>` via [rawArrayFunc].
class RTempStructPtrAlloc<C extends Struct, D extends StructD<C, D>> extends RTempAlloc<Pointer<C>> {

  /// Converts an `D` of Dart struct wrapper into an allocated `Pointer<C>` pointer.
  Pointer<C> Function([D?, String?]) valueFunc;

  /// Converts a `List<D>` of Dart struct wrappers into an allocated `Pointer<C>` array.
  Pointer<C> Function(List<D> array) rawArrayFunc;

  /// Overwrites the [i]-th element of the array at [ptr] with [value].
  void Function(Pointer<Pointer<C>> ptr, int i, Pointer<C> value) indexSetterFunc;

  RTempStructPtrAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.valueFunc,
    required this.rawArrayFunc,
    required this.indexSetterFunc,
  });

  /// Allocates an unslotted `Pointer<Pointer<C>>` of [count] elements.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<C>> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted pointer-of-pointers from a list of struct arrays.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<C>> RawArray(List<List<D>> arrays) {
    final p = Raw(arrays.length);
    for (int i = 0; i < arrays.length; i++) p[i] = rawArrayFunc(arrays[i]);
    return p;
  }

  /// Writes [array] into a tracked slot of sufficient capacity.
  Pointer<Pointer<C>> Array(List<D> array, {String? key}) {
    key ??= slotKey(key);
    final p = At(key, array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, valueFunc(array[i], '${key}_$i'));
    return p;
  }

  /// Writes each sub-array in [arrays] into a tracked slot and returns the
  /// outer `Pointer<Pointer<C>>`
  Pointer<Pointer<C>> Fill(List<List<D>> arrays, {String? key}) {
    final p = At(slotKey(key), arrays.length);
    for (int i = 0; i < arrays.length; i++) p[i] = rawArrayFunc(arrays[i]);
    return p;
  }

  /// Fills a tracked slot of [count] pointers by calling `init(i)` for each index.
  Pointer<Pointer<C>> FillRaw(int count, Pointer<C> Function(int) init, {String? key}) {
    final pp = At(slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }
}

/// A specialised slot-based allocator for C strings ([Pointer\<Char>]).
///
/// Maintains two separate pools:
/// - **Anonymous slots** – a ring buffer of [slotCount] slots, cycled through
///   via [Value] without a key. Useful for transient strings within a single callsite.
/// - **Keyed slots** – named slots allocated on demand via [ValueAt] and
///   [Array], persisting until explicitly freed or [_dispose] is called.
///
/// String memory is managed with [malloc] and is grown in-place when the
/// encoded UTF-8 length of a new string exceeds the current slot capacity,
/// avoiding unnecessary reallocations for strings of similar length.
final class RTempStringAlloc extends RTempAlloc<Pointer<Char>> {

  /// Number of anonymous (ring-buffer) string slots pre-reserved on construction.
  final int slotCount;

  RTempStringAlloc(super.temp, super.name, {
    required this.slotCount,
    required super.allocatorFunc,
    required super.printerFunc,
  }) { _reset(); }

  final Map<String, int> _StringSlotsKeyed = {};
  List<Pointer<Char>> _StringSlots = [];
  List<int> _StringCapacities = [];
  int _StringAnonIndex = 0;

  /// Resets all slot bookkeeping structures to their initial state.
  ///
  /// Called during construction and at the end of [_dispose].
  void _reset() {
    // NOTE: needs to be growable
    _StringSlots = .filled(slotCount, nullptr, growable: true);
    _StringCapacities = .filled(slotCount, 0, growable: true);
    _StringAnonIndex = 0;
  }

  /// Allocates and returns an unslotted array of [count] `Pointer<Char>` pointers.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<Char>> Raw([int count = 1]) => allocatorFunc(count);

  /// Writes each string in [array] into keyed sub-slots and returns a tracked
  /// `Pointer<Pointer<Char>>` of length `array.length`.
  ///
  /// Sub-slot keys follow the pattern `'<key>_<i>'`. [key] defaults to
  /// `'default'`.
  Pointer<Pointer<Char>> Array(List<String> array, {String? key}) {
    final arrayKey = slotKey(key);
    final pp = At(arrayKey, array.length);
    for (int i = 0; i < array.length; i++) pp[i] = ValueAt('${arrayKey}_$i', array[i]);
    return pp;
  }

  /// Fills a tracked [Pointer<Pointer<Char>>] of [count] elements by calling
  /// [init](i) for each index.
  Pointer<Pointer<Char>> Fill(int count, Pointer<Char> Function(int) init, {String? key}) {
    final pp = At(slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }

  /// Returns a `Pointer<Char>` for [text] using the next anonymous ring-buffer slot.
  /// 
  /// Anonymous slots cycle modulo [slotCount], so older anonymous strings may be overwritten.
  /// 
  /// If [key] is provided, delegates to [ValueAt] instead.
  Pointer<Char> Value(String text, [String? key]) {
    if (key != null) return ValueAt(key, text);
    final slot = _StringAnonIndex;
    _StringAnonIndex = (_StringAnonIndex + 1) % slotCount;
    _ensureStringSlotExists(slot);
    return _writeStringToSlot(slot, text);
  }

  /// Writes [text] into slot using `Value` and returns its pointer, or returns [nullptr]
  /// if [text] is `null`.
  ///
  /// Use this instead of [Value] when the C API uses a null pointer to signal "no value".
  Pointer<Char> ValueOrNull([String? text, String? key])
    => text == null ? nullptr : Value(text, key);

  /// Returns the `Pointer<Char>` for the keyed slot [key], optionally writing
  /// [text] into it.
  ///
  /// Allocates the slot on first use. If [text] is `null` the existing string
  /// is returned; asserts that the slot has been initialised at least once.
  Pointer<Char> ValueAt(String key, [String? text]) {
    final slot = _StringSlotsKeyed.putIfAbsent(
      key, () => _StringSlots.length
    );

    _ensureStringSlotExists(slot);

    if (text != null) {
      return _writeStringToSlot(slot, text);
    }

    assert(
      _StringSlots[slot] != nullptr,
      '[TEMP] String.ValueAt("$key") used before initialization'
    );

    return _StringSlots[slot];
  }

  /// Ensures the slot list is large enough to hold index [slot], growing it
  /// with null-pointer sentinels if necessary.
  void _ensureStringSlotExists(int slot) {
    if (slot < _StringSlots.length) return;

    final growBy = slot + 1 - _StringSlots.length;

    _StringSlots.addAll(List.filled(growBy, nullptr));
    _StringCapacities.addAll(List.filled(growBy, 0));
  }

  /// Writes [text] into slot [slot], reallocating if the current capacity is
  /// insufficient for the UTF-8 encoded length.
  ///
  /// Always null-terminates the written string.
  Pointer<Char> _writeStringToSlot(int slot, String text) {
    final encoded = utf8.encode(text);
    final requiredBytes = encoded.length + 1;

    if (
      _StringSlots[slot] == nullptr ||
      _StringCapacities[slot] < requiredBytes
    ) {
      if (_StringSlots[slot] != nullptr) {
        malloc.free(_StringSlots[slot]);
      }

      _StringSlots[slot] = malloc.allocate<Char>(requiredBytes);
      _StringCapacities[slot] = requiredBytes;
    }

    final dst = _StringSlots[slot]
      .cast<Uint8>()
      .asTypedList(requiredBytes);

    dst.setAll(0, encoded);
    dst[encoded.length] = 0;

    return _StringSlots[slot];
  }

  @override
  void Free(String key) {
    if (!_StringSlotsKeyed.containsKey(key)) {
      throw StateError('[FREE] Cannot free unallocated String slot $key');
    }

    int slot = _StringSlotsKeyed[key]!;
    calloc.free(_StringSlots[slot]);
    _StringSlotsKeyed.remove(key);
    _StringSlots.removeAt(slot);
    _StringCapacities.removeAt(slot);
  }

  @override
  void _dispose() {
    if (_StringSlots.isNotEmpty) {
      final nonNulls = _StringSlots.where((e) => e != nullptr);
      temp.debugFreeInfo('Freeing preallocated $slotCount $name slots (used ${nonNulls.length})');
      nonNulls.forEach(calloc.free);
    }
    if (_StringSlotsKeyed.isNotEmpty) {
      temp.debugFreeInfo('Freeing user-defined ${_StringSlotsKeyed.length} $name slots');
    }
    _reset();
  }

  /// Writes [o] into slot `'1'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '1')`. Use [RefOrNull1] if [o] may be `null`
  /// and the callee expects [nullptr] in that case.
  Pointer<Char> Ref1([String? o]) => ValueAt('1', o);

  /// Writes [o] into slot `'2'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '2')`. Use [RefOrNull2] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<Char> Ref2([String? o]) => ValueAt('2', o);

  /// Writes [o] into slot `'3'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '3')`. Use [RefOrNull3] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<Char> Ref3([String? o]) => ValueAt('3', o);

  /// Writes [o] into slot `'4'` and returns its pointer.
  ///
  /// Shorthand for `Value(o, '4')`. Use [RefOrNull4] if [o] may be `null`
  /// and the callee expects [nullptr] in that case..
  Pointer<Char> Ref4([String? o]) => ValueAt('4', o);

  /// Writes [o] into slot `'1'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref1] when the C API uses a null pointer to signal "no value".
  Pointer<Char> RefOrNull1(String? o) => o == null ? nullptr : Ref1(o);

  /// Writes [o] into slot `'2'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref2] when the C API uses a null pointer to signal "no value".
  Pointer<Char> RefOrNull2(String? o) => o == null ? nullptr : Ref2(o);

  /// Writes [o] into slot `'3'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref3] when the C API uses a null pointer to signal "no value".
  Pointer<Char> RefOrNull3(String? o) => o == null ? nullptr : Ref3(o);

  /// Writes [o] into slot `'4'` and returns its pointer, or returns [nullptr]
  /// if [o] is `null`.
  ///
  /// Use this instead of [Ref4] when the C API uses a null pointer to signal "no value".
  Pointer<Char> RefOrNull4(String? o) => o == null ? nullptr : Ref4(o);
}

class RaylibTemp extends RaylibTempBase<Raylib> {
  final RaylibTempOptions options;

  RaylibTemp(super.lib, {
    this.options = const RaylibTempOptions(),
  }) {
    _init();
    _preAllocate();
    _preAllocateReusables();
  }

  late Map<String, RTempAlloc> _allocators;

  late RTempStringAlloc String$;

/*{{ALLOCATORS_PROPERTIES}}*/

  /// ===========================
  /// ====== CUSTOM ALLOCS ======
  /// ===========================

  final Map<String, RTempAlloc> _customAllocators = {};
  
  void registerAllocator(String key, RTempAlloc alloc) {
    if (_customAllocators.containsKey(key)) {
      final sig = _customAllocators[key]!.signature();
      throw StateError("Allocator '$key' ('$sig') already exists!");
    }

    _customAllocators[key] = alloc;
  }

  RTempAlloc _getCustomAllocatorOrThrow(String key) {
    final alloc = _customAllocators[key];
    if (alloc == null) throw StateError("No custom allocator registered for '$key'!");
    return alloc;
  }

  T alloc<T extends RTempAlloc>(String key) => _customAllocators[key] as T;

  RTempLitAlloc<X, C> allocLit<X, C extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitAlloc<X, C>;

  RTempLitTypedIntListAlloc<X, C, L> allocIntList<X, C extends NativeType, L extends TypedDataList>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitTypedIntListAlloc<X, C, L>;

  RTempLitTypedFloatListAlloc<X, C, L> allocFloatList<X, C extends NativeType, L extends TypedDataList>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitTypedFloatListAlloc<X, C, L>;

  RTempLitPtrAlloc<X, C> allocLitPtr<X, C extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitPtrAlloc<X, C>;

  RTempStructAlloc<C, D> allocStruct<C extends Struct, D extends StructD<C, D>>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempStructAlloc<C, D>;

  RTempStructPtrAlloc<C, D> allocStructPtr<C extends Struct, D extends StructD<C, D>>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempStructPtrAlloc<C, D>;

  /// ============================
  /// ====== INITIALIZATION ======
  /// ============================

  void _init() {
    if (options.stringCount > 0) {
      logInfo('[TEMP] Allocating ${options.stringCount} String slots');
    }

    String$ = .new(this, 'String\$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Char>>(count),
      printerFunc: (ptr) => ptr.value.toD,
      slotCount: options.stringCount,
    );

/*{{ALLOCATORS_INITIALIZATION}}*/

    _allocators = {
      String$.name: String$,
      
/*{{ALLOCATORS_MAP_ENTRIES}}*/
    };
  }

  Pointer<Char> str(String text) => String$.Value(text);
  Pointer<Char> strAt(String key, [String? text]) => String$.ValueAt(key, text);

  @override
  void dispose() {
    super.dispose();

    debugFreeInfo('Freeing preallocated internals');
    _dePreAllocate();
    
    debugFreeInfo('Freeing preallocated reusable internals');
    _dePreAllocateReusables();

    debugFreeInfo('Freeing ${_allocators.length} built-in allocators');
    _allocators.values.forEach((a) => a._dispose());

    if (_customAllocators.isNotEmpty) {
      debugFreeInfo('Freeing ${_customAllocators.length} custom allocators');
      _customAllocators.values.forEach((a) => a._dispose());
    }
  }

  /// ======================================
  /// ====== PRE-ALLOCATED IMMUTABLES ======
  /// ======================================
  /// 1x  Vector2 => 1 * ( 2*float) => 1 * ( 2*4) =>  8 Bytes
  /// 1x  Vector3 => 1 * ( 3*float) => 1 * ( 3*4) => 12 Bytes
  /// 1x  Vector4 => 1 * ( 4*float) => 1 * ( 4*4) => 16 Bytes
  /// 2x   Matrix => 2 * (16*float) => 2 * (16*4) => 128 Bytes
  /// 1x     Quat => 1 * ( 4*float) => 1 * ( 4*4) => 16 Bytes
  /// ====================================
  /// Total preallocated memory: 180 Bytes
  /// 
  /// NOTE: We do not use slots to not make logs look suspicious
  /// NOTE: Pointers are private, because 'immutables' are meant to be immutable
  ///       (though you can mutate the references)
  
  late Pointer<Vector2C> _vec2ZeroPtr;
  Vector2C get vec2Zero => _vec2ZeroPtr.ref;

  late Pointer<Vector3C> _vec3ZeroPtr;
  Vector3C get vec3Zero => _vec3ZeroPtr.ref;
  
  late Pointer<Vector4C> _vec4ZeroPtr;
  Vector4C get vec4Zero => _vec4ZeroPtr.ref;
  
  late Pointer<MatrixC> _matZeroPtr;
  MatrixC get matZero => _matZeroPtr.ref;
  
  late Pointer<MatrixC> _matIdentityPtr;
  MatrixC get matIdentity => _matIdentityPtr.ref;
  
  late Pointer<QuaternionC> _quatIdentityPtr;
  QuaternionC get quatIdentity => _quatIdentityPtr.ref;

  void _preAllocate() {
    _vec2ZeroPtr = calloc<Vector2C>();
    _vec3ZeroPtr = calloc<Vector3C>();
    _vec4ZeroPtr = calloc<Vector4C>();
    _matZeroPtr = calloc<MatrixC>();
    _matIdentityPtr = calloc<MatrixC>().setD(.identity());
    _quatIdentityPtr = calloc<QuaternionC>().setD(.identity());
  }

  void _dePreAllocate() {
    calloc.free(_vec2ZeroPtr);
    calloc.free(_vec3ZeroPtr);
    calloc.free(_vec4ZeroPtr);
    calloc.free(_matZeroPtr);
    calloc.free(_matIdentityPtr);
  }

  /// =====================================
  /// ====== PRE-ALLOCATED REUSABLES ======
  /// =====================================
  /// 4x   Vector2 => 4 * (2*float)         => 4 * (2*4) => 32 Bytes
  /// 4x   Vector3 => 4 * (3*float)         => 4 * (3*4) => 48 Bytes
  /// 4x   Vector4 => 4 * (4*float)         => 4 * (4*4) => 64 Bytes
  /// 4x     Color => 4 * (4*unsigned char) => 4 * (4*1) => 16 Bytes
  /// 4x Rectangle => 4 * (4*float)         => 4 * (4*4) => 64 Bytes
  /// ====================================
  /// Total preallocated memory: 224 Bytes
  /// 
  /// NOTE: We do not use slots to not make logs look suspicious

  /// Vector2
  
  late Pointer<Vector2C> vec21Ptr;
  Vector2C vec21([num? x, num? y])
    => vec21Ptr.set(x ?? vec21Ptr.ref.x, y ?? vec21Ptr.ref.y).ref;
  Vector2C vec21C(Vector2C o) => vec21(o.x, o.y);
  Vector2C vec21D(Vector2D o) => vec21(o.x, o.y);

  late Pointer<Vector2C> vec22Ptr;
  Vector2C vec22([num? x, num? y])
    => vec22Ptr.set(x ?? vec22Ptr.ref.x, y ?? vec22Ptr.ref.y).ref;
  Vector2C vec22C(Vector2C o) => vec22(o.x, o.y);
  Vector2C vec22D(Vector2D o) => vec22(o.x, o.y);

  late Pointer<Vector2C> vec23Ptr;
  Vector2C vec23([num? x, num? y])
    => vec23Ptr.set(x ?? vec23Ptr.ref.x, y ?? vec23Ptr.ref.y).ref;
  Vector2C vec23C(Vector2C o) => vec23(o.x, o.y);
  Vector2C vec23D(Vector2D o) => vec23(o.x, o.y);

  late Pointer<Vector2C> vec24Ptr;
  Vector2C vec24([num? x, num? y])
    => vec24Ptr.set(x ?? vec24Ptr.ref.x, y ?? vec24Ptr.ref.y).ref;
  Vector2C vec24C(Vector2C o) => vec24(o.x, o.y);
  Vector2C vec24D(Vector2D o) => vec24(o.x, o.y);

  /// Vector3

  late Pointer<Vector3C> vec31Ptr;
  Vector3C vec31([num? x, num? y, num? z])
    => vec31Ptr.set(x ?? vec31Ptr.ref.x, y ?? vec31Ptr.ref.y, z ?? vec31Ptr.ref.z).ref;
  Vector3C vec31C(Vector3C o) => vec31(o.x, o.y, o.z);
  Vector3C vec31D(Vector3D o) => vec31(o.x, o.y, o.z);
    
  late Pointer<Vector3C> vec32Ptr;
  Vector3C vec32([num? x, num? y, num? z])
    => vec32Ptr.set(x ?? vec32Ptr.ref.x, y ?? vec32Ptr.ref.y, z ?? vec32Ptr.ref.z).ref;
  Vector3C vec32C(Vector3C o) => vec32(o.x, o.y, o.z);
  Vector3C vec32D(Vector3D o) => vec32(o.x, o.y, o.z);

  late Pointer<Vector3C> vec33Ptr;
  Vector3C vec33([num? x, num? y, num? z])
    => vec33Ptr.set(x ?? vec33Ptr.ref.x, y ?? vec33Ptr.ref.y, z ?? vec33Ptr.ref.z).ref;
  Vector3C vec33C(Vector3C o) => vec33(o.x, o.y, o.z);
  Vector3C vec33D(Vector3D o) => vec33(o.x, o.y, o.z);

  late Pointer<Vector3C> vec34Ptr;
  Vector3C vec34([num? x, num? y, num? z])
    => vec34Ptr.set(x ?? vec34Ptr.ref.x, y ?? vec34Ptr.ref.y, z ?? vec34Ptr.ref.z).ref;
  Vector3C vec34C(Vector3C o) => vec34(o.x, o.y, o.z);
  Vector3C vec34D(Vector3D o) => vec34(o.x, o.y, o.z);

  /// Vector4

  late Pointer<Vector4C> vec41Ptr;
  Vector4C vec41([num? x, num? y, num? z, num? w])
    => vec41Ptr.set(x ?? vec41Ptr.ref.x, y ?? vec41Ptr.ref.y, z ?? vec41Ptr.ref.z, w ?? vec41Ptr.ref.w).ref;
  Vector4C vec41C(Vector4C o) => vec41(o.x, o.y, o.z);
  Vector4C vec41D(Vector4D o) => vec41(o.x, o.y, o.z);
    
  late Pointer<Vector4C> vec42Ptr;
  Vector4C vec42([num? x, num? y, num? z, num? w])
    => vec42Ptr.set(x ?? vec42Ptr.ref.x, y ?? vec42Ptr.ref.y, z ?? vec42Ptr.ref.z, w ?? vec42Ptr.ref.w).ref;
  Vector4C vec42C(Vector4C o) => vec42(o.x, o.y, o.z);
  Vector4C vec42D(Vector4D o) => vec42(o.x, o.y, o.z);

  late Pointer<Vector4C> vec43Ptr;
  Vector4C vec43([num? x, num? y, num? z, num? w])
    => vec43Ptr.set(x ?? vec43Ptr.ref.x, y ?? vec43Ptr.ref.y, z ?? vec43Ptr.ref.z, w ?? vec43Ptr.ref.w).ref;
  Vector4C vec43C(Vector4C o) => vec43(o.x, o.y, o.z);
  Vector4C vec43D(Vector4D o) => vec43(o.x, o.y, o.z);

  late Pointer<Vector4C> vec44Ptr;
  Vector4C vec44([num? x, num? y, num? z, num? w])
    => vec44Ptr.set(x ?? vec44Ptr.ref.x, y ?? vec44Ptr.ref.y, z ?? vec44Ptr.ref.z, w ?? vec44Ptr.ref.w).ref;
  Vector4C vec44C(Vector4C o) => vec44(o.x, o.y, o.z);
  Vector4C vec44D(Vector4D o) => vec44(o.x, o.y, o.z);

  /// Color

  late Pointer<ColorC> color1Ptr;
  ColorC color1([num? r, num? g, num? b, num? a])
    => color1Ptr.set(r ?? color1Ptr.ref.r, g ?? color1Ptr.ref.g, b ?? color1Ptr.ref.b, a ?? color1Ptr.ref.a).ref;
  ColorC color1C(ColorC o) => color1(o.r, o.g, o.b, o.a);
  ColorC color1D(ColorD o) => color1(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color2Ptr;
  ColorC color2([num? r, num? g, num? b, num? a])
    => color2Ptr.set(r ?? color2Ptr.ref.r, g ?? color2Ptr.ref.g, b ?? color2Ptr.ref.b, a ?? color2Ptr.ref.a).ref;
  ColorC color2C(ColorC o) => color2(o.r, o.g, o.b, o.a);
  ColorC color2D(ColorD o) => color2(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color3Ptr;
  ColorC color3([num? r, num? g, num? b, num? a])
    => color3Ptr.set(r ?? color3Ptr.ref.r, g ?? color3Ptr.ref.g, b ?? color3Ptr.ref.b, a ?? color3Ptr.ref.a).ref;
  ColorC color3C(ColorC o) => color3(o.r, o.g, o.b, o.a);
  ColorC color3D(ColorD o) => color3(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color4Ptr;
  ColorC color4([num? r, num? g, num? b, num? a])
    => color4Ptr.set(r ?? color4Ptr.ref.r, g ?? color4Ptr.ref.g, b ?? color4Ptr.ref.b, a ?? color4Ptr.ref.a).ref;
  ColorC color4C(ColorC o) => color4(o.r, o.g, o.b, o.a);
  ColorC color4D(ColorD o) => color4(o.r, o.g, o.b, o.a);

  /// Rectangle

  late Pointer<RectangleC> rect1Ptr;
  RectangleC rect1([num? x, num? y, num? w, num? h])
    => rect1Ptr.set(x ?? rect1Ptr.ref.x, y ?? rect1Ptr.ref.y, w ?? rect1Ptr.ref.width, h ?? rect1Ptr.ref.height).ref;
  RectangleC rect1C(RectangleC o) => rect1(o.x, o.y, o.width, o.height);
  RectangleC rect1D(RectangleD o) => rect1(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect2Ptr;
  RectangleC rect2([num? x, num? y, num? w, num? h])
    => rect2Ptr.set(x ?? rect2Ptr.ref.x, y ?? rect2Ptr.ref.y, w ?? rect2Ptr.ref.width, h ?? rect2Ptr.ref.height).ref;
  RectangleC rect2C(RectangleC o) => rect2(o.x, o.y, o.width, o.height);
  RectangleC rect2D(RectangleD o) => rect2(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect3Ptr;
  RectangleC rect3([num? x, num? y, num? w, num? h])
    => rect3Ptr.set(x ?? rect3Ptr.ref.x, y ?? rect3Ptr.ref.y, w ?? rect3Ptr.ref.width, h ?? rect3Ptr.ref.height).ref;
  RectangleC rect3C(RectangleC o) => rect3(o.x, o.y, o.width, o.height);
  RectangleC rect3D(RectangleD o) => rect3(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect4Ptr;
  RectangleC rect4([num? x, num? y, num? w, num? h])
    => rect4Ptr.set(x ?? rect4Ptr.ref.x, y ?? rect4Ptr.ref.y, w ?? rect4Ptr.ref.width, h ?? rect4Ptr.ref.height).ref;
  RectangleC rect4C(RectangleC o) => rect4(o.x, o.y, o.width, o.height);
  RectangleC rect4D(RectangleD o) => rect4(o.x, o.y, o.width, o.height);

  void _preAllocateReusables() {
    vec21Ptr = calloc<Vector2C>();
    vec22Ptr = calloc<Vector2C>();
    vec23Ptr = calloc<Vector2C>();
    vec24Ptr = calloc<Vector2C>();

    vec31Ptr = calloc<Vector3C>();
    vec32Ptr = calloc<Vector3C>();
    vec33Ptr = calloc<Vector3C>();
    vec34Ptr = calloc<Vector3C>();
    
    vec41Ptr = calloc<Vector4C>();
    vec42Ptr = calloc<Vector4C>();
    vec43Ptr = calloc<Vector4C>();
    vec44Ptr = calloc<Vector4C>();
    
    color1Ptr = calloc<ColorC>();
    color2Ptr = calloc<ColorC>();
    color3Ptr = calloc<ColorC>();
    color4Ptr = calloc<ColorC>();
    
    rect1Ptr = calloc<RectangleC>();
    rect2Ptr = calloc<RectangleC>();
    rect3Ptr = calloc<RectangleC>();
    rect4Ptr = calloc<RectangleC>();
  }

  void _dePreAllocateReusables() {
    calloc.free(vec21Ptr);
    calloc.free(vec22Ptr);
    calloc.free(vec23Ptr);
    calloc.free(vec24Ptr);

    calloc.free(vec31Ptr);
    calloc.free(vec32Ptr);
    calloc.free(vec33Ptr);
    calloc.free(vec34Ptr);
    
    calloc.free(vec41Ptr);
    calloc.free(vec42Ptr);
    calloc.free(vec43Ptr);
    calloc.free(vec44Ptr);
    
    calloc.free(color1Ptr);
    calloc.free(color2Ptr);
    calloc.free(color3Ptr);
    calloc.free(color4Ptr);

    calloc.free(rect1Ptr);
    calloc.free(rect2Ptr);
    calloc.free(rect3Ptr);
    calloc.free(rect4Ptr);
  }
}