part of '../raylib.dart';

/*
  This file is automatically generated!
  Do not modify it directly!

  Modify the template: `utils/templates/temp.dart`
  Generated using: `utils/generators/temp.dart`

  =============================================
  ====== PRE-ALLOCATED MEMORY STATISTICS ======
  =============================================
   IMMUTABLES: 180 Bytes
    REUSABLES: 224 Bytes
  =============================================
             : 404 Bytes
*/

class RaylibTempOptions {
  final int stringCount;

  const RaylibTempOptions({
    this.stringCount = 4,
  });
}

/// A slot-based temporary memory allocator for a single native type [T].
///
/// Manages a named collection of `Pointer<T>` slots identified by string keys.
/// Each slot owns its allocation; slots are freed either manually via [Free]
/// or automatically when [_dispose] is called (e.g. at the end of a frame).
///
/// Subclasses specialise this for literal values, structs, strings, etc.
abstract class RTempAlloc<T extends NativeType> {

  /// The parent [RaylibTemp] context that owns this allocator.
  final RaylibTemp _temp;
  
  /// Human-readable name for this allocator, used in debug/log messages.
  final String name;
  
  /// Low-level allocation function. Called with an element [count] and
  /// returns a freshly allocated `Pointer<T>`.
  Pointer<T> Function([int count]) allocatorFunc;
  
  /// Debug printer: converts a `Pointer<T>` to a human-readable string.
  String Function(Pointer<T> ptr) printerFunc;

  RTempAlloc(RaylibTemp temp, this.name, {
    required this.allocatorFunc,
    required this.printerFunc,
  }) : _temp = temp;

  final Map<String, (Pointer<T>, int)> _Slots = {};

  /// Returns a string that identifies the concrete type of this allocator,
  /// including its type parameters (e.g. `"RTempAlloc<Float>"`).
  String signature() => '$runtimeType<$T>';

  /// Returns the canonical slot key for [key], falling back to `'default'`
  /// when [key] is `null`.
  String _slotKey([String? key]) => key ?? 'default';

  /// Returns the `Pointer<T>` stored in [key], allocating (or reallocating)
  /// if necessary.
  ///
  /// If the slot already exists and its current capacity is >= [count], the
  /// existing pointer is reused. If capacity is insufficient the old block is
  /// freed and a new one of size [count] is allocated.
  ///
  /// [key]   – slot identifier (must not be null).
  /// [count] – minimum element capacity required (default: 1).
  Pointer<T> At(String key, [int count = 1]) {
    final existing = _Slots[key];
    if (existing != null) {
      final (ptr, currentCount) = existing;

      if (count <= currentCount) {
        // _temp.logInfo('[TEMP] Reusing slot for $T at $key with $count');
        _Slots[key] = (ptr, count);
        return ptr;
      }
      
      calloc.free(ptr);
    }
    // _temp.logInfo('[TEMP] Creating slot for $T at $key with $count');
    final ptr = allocatorFunc(count);
    _Slots[key] = (ptr, count);
    return ptr;
  }

  /// Returns the pointer stored under [key], or `null` if the slot does not
  /// exist. Does **not** allocate.
  Pointer<T>? Slot(String key) => _Slots[_slotKey(key)]?.$1;

  /// Returns `true` if a slot with the given [key] exists.
  bool Has(String key) => _Slots.containsKey(_slotKey(key));

  /// Frees the native memory owned by slot [key] and removes it from the
  /// table.
  ///
  /// Throws if [key] has not been allocated.
  void Free(String key) {
    if (!_Slots.containsKey(key)) {
      throw StateError('[FREE] Cannot free unallocated slot $key');
    }
    calloc.free(_Slots[key]!.$1);
    _Slots.remove(key);
  }

  /// Removes the slot entry for [key] from the table **without** freeing the
  /// underlying memory.
  ///
  /// Use when ownership of the pointer has been transferred elsewhere.
  void Unslot(String key) => _Slots.remove(_slotKey(key));

  /// Frees all currently tracked slots and clears the slot table.
  ///
  /// Called automatically by the owning [RaylibTemp] during disposal.
  void _dispose() {
    if (_Slots.isNotEmpty) {
      _temp.debugFreeInfo('Freeing user-defined ${_Slots.length} $name slots');
      _Slots.entries.forEach((x) {
        _temp.debugFreeInfo('[FREE] ${x.key}');
        calloc.free(x.value.$1);
      });
      _Slots.clear();
    }
  }
}

/// A [RTempAlloc] that also knows how to write Dart values of type [X] into
/// native [T] memory, and supports typed-list array operations.
///
/// [X] is the Dart-side value type (e.g. `int`, `double`).
/// [T] is the corresponding [NativeType] (e.g. `Int32`, `Float`).
class RTempLitAlloc<X, T extends NativeType> extends RTempAlloc<T> {
  
  /// Casts an untyped [Pointer] to `Pointer<T>`.
  Pointer<T> Function(Pointer ptr) castFunc;
  
  /// Returns the size in bytes of a single [T] element.
  int Function() sizeOfFunc;
  
  /// Writes a single Dart value [value] into the memory pointed to by [ptr].
  void Function(Pointer<T> ptr, X value) literalSetterFunc;
  
  /// Writes [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<T> ptr, int i, X value) indexSetterFunc;

  RTempLitAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.castFunc,
    required this.sizeOfFunc,
    required this.literalSetterFunc,
    required this.indexSetterFunc,
  });
  
  @override
  String signature() => '$runtimeType<$X, $T>';

  /// Returns the total byte size for [count] elements.
  int Size([int count = 1]) => count*sizeOfFunc();

  /// Allocates a fresh (unslotted) block of [count] elements and returns it.
  ///
  /// The caller is responsible for freeing this pointer.
  Pointer<T> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted array and populates it from [array].
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<T> RawArray(List<X> array) {
    final p = Raw(array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, array[i]);
    return p;
  }

  /// Returns the pointer for the slot identified by [key] (default: `'default'`),
  /// writing [value] into it when provided.
  ///
  /// Allocates the slot on first use.
  Pointer<T> Value([X? value, String? key]) {
    final p = At(_slotKey(key));
    if (value != null) literalSetterFunc(p, value);
    return p;
  }

  /// Writes [array] into a slot of sufficient capacity and returns the pointer.
  ///
  /// [key] defaults to `'default'`. The slot is grown automatically if the
  /// current capacity is smaller than `array.length`.
  Pointer<T> Array(List<X> array, {String? key}) {
    final p = At(_slotKey(key), array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, array[i]);
    return p;
  }

  /// Allocates (or reuses) a slot of [count] elements, populating each index
  /// [i] with the value returned by `init(i)`.
  Pointer<T> Fill(int count, X Function(int) init, {String? key}) {
    final p = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(i));
    return p;
  }
}

/// Extends [RTempLitAlloc] with typed-list bulk copy support.
///
/// [asTypedList] bridges between the native pointer and a Dart [TypedDataList],
/// enabling zero-copy bulk memory operations.
abstract class RTempLitTypedListAlloc<X, T extends NativeType> extends RTempLitAlloc<X, T> {

  /// Wraps [ptr] as a Dart [TypedDataList] of [length] elements.
  ///
  /// The list is a **view** into native memory, so mutations are reflected
  /// immediately in the native buffer.
  TypedDataList Function(Pointer<T> ptr, int length) asTypedList;

  RTempLitTypedListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required this.asTypedList,
  });

  @override
  String signature() => '$runtimeType<$X, $T>';

  /// Copies [length] elements from [src] into a slot and returns the pointer.
  ///
  /// Uses [asTypedList] for the bulk copy, which avoids an element-by-element
  /// loop. [key] defaults to `'default'`.
  Pointer<T> Copy(Pointer<T> src, int length, {String? key}) {
    final p = At(_slotKey(key), length);
    final srcList = asTypedList(castFunc(src), length);
    asTypedList(castFunc(p), length).setAll(0, srcList);
    return p;
  }
}

/// A typed-list allocator for integer native types (e.g. `Int32`, `Uint8`).
///
/// Adds byte-serialisation helpers that convert the native integer array to
/// big-endian or little-endian byte lists, useful for hashing and I/O.
class RTempLitTypedIntListAlloc<X, T extends NativeType> extends RTempLitTypedListAlloc<X, T> {

  /// Returns a Dart [List<int>] view of [length] integer elements at [ptr].
  List<int> Function(Pointer<T> ptr, int length) asDartList;

  RTempLitTypedIntListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required super.asTypedList,
    required this.asDartList,
  });

  @override
  String signature() => '$runtimeType<$X, $T>';

  /// Serialises [length] words starting at [ptr] to a flat big-endian byte list.
  ///
  /// Each word is split into `sizeOf<T>()` bytes, most-significant byte first.
  List<int> ToBEBytes(Pointer<T> ptr, int length) {
    final wordSize = sizeOfFunc();
    return asDartList(ptr, length).expand((word) =>
      .generate(wordSize, (i) => (word >> ((wordSize - 1 - i) * 8)) & 0xFF)
    ).toList();
  }

  /// Serialises [length] words starting at [ptr] to a flat little-endian byte list.
  ///
  /// Each word is split into `sizeOf<T>()` bytes, least-significant byte first.
  List<int> ToLEBytes(Pointer<T> ptr, int length) {
    final wordSize = sizeOfFunc();
    return asDartList(ptr, length).expand((word) =>
      .generate(wordSize, (i) => (word >> (i * 8)) & 0xFF)
    ).toList();
  }
}

/// A typed-list allocator for floating-point native types (e.g. `Float`, `Double`).
class RTempLitTypedFloatListAlloc<X, T extends NativeType> extends RTempLitTypedListAlloc<X, T> {
  List<double> Function(Pointer<T> ptr, int length) asDartList;

  RTempLitTypedFloatListAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required super.castFunc,
    required super.sizeOfFunc,
    required super.literalSetterFunc,
    required super.indexSetterFunc,
    required super.asTypedList,
    required this.asDartList,
  });

  @override
  String signature() => '$runtimeType<$X, $T>';
}

/// A slot-based allocator for arrays of **pointers** to literal elements.
///
/// Manages `Pointer<Pointer<T>>` slots; each inner pointer is produced by
/// [rawArrayFunc] from a `List<X>`.
class RTempLitPtrAlloc<X, T extends NativeType> extends RTempAlloc<Pointer<T>> {

  /// Converts a flat `List<X>` into an allocated `Pointer<T>` array.
  ///
  /// The caller is responsible for the lifetime of the inner pointers.
  Pointer<T> Function(List<X> array) rawArrayFunc;

  RTempLitPtrAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.rawArrayFunc,
  });

  @override
  String signature() => '$runtimeType<$X, $T>';

  /// Allocates an unslotted `Pointer<Pointer<T>>` of [count] elements.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<T>> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted pointer-of-pointers from a list of value arrays.
  ///
  /// Each `arrays[i]` is converted via [rawArrayFunc].
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<T>> RawArray(List<List<X>> arrays) {
    final pp = Raw(arrays.length);
    for (int i = 0; i < arrays.length; i++) {
      pp[i] = rawArrayFunc(arrays[i]);
    }
    return pp;
  }

  /// Writes each sub-array in [arrays] into a tracked slot via [rawArrayFunc]
  /// and returns the outer `Pointer<Pointer<T>>]`
  Pointer<Pointer<T>> Fill(List<List<X>> arrays, {String? key}) {
    final pp = At(_slotKey(key), arrays.length);
    for (int i = 0; i < arrays.length; i++) pp[i] = rawArrayFunc(arrays[i]);
    return pp;
  }

  /// Fills a tracked slot of [count] pointers by calling `init(i)` for each
  /// index and storing the result.
  Pointer<Pointer<T>> FillRaw(int count, Pointer<T> Function(int) init, {String? key}) {
    final pp = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }
}

/// A slot-based allocator for native structs of type [T], accepting Dart-side
/// [StructD] wrappers of type [X].
///
/// Bridges between the ergonomic Dart [StructD] layer and raw `Pointer<T>`
/// memory, supporting both single-value and array slots.
class RTempStructAlloc<T extends Struct, X extends StructD<X, T>> extends RTempAlloc<T> {

  /// Casts an untyped [Pointer] to `Pointer<T>`.
  Pointer<T> Function(Pointer ptr) castFunc;

  /// Returns the size in bytes of a single [T] struct.
  int Function() sizeOfFunc;
  
  /// Writes the Dart value [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<T> ptr, int i, X value) writeIntoIndexedFunc;
  
  /// Writes the Dart value [value] into the struct at [ptr].
  void Function(Pointer<T> ptr, X value) writeIntoFunc;
  
  /// Copies the raw C struct [value] into the [i]-th element of the array at [ptr].
  void Function(Pointer<T> ptr, int i, T value) setCFunc;
  
  /// Returns the [T] struct at index [i] of the array at [ptr].
  T Function(Pointer<T> ptr, int i) indexerFunc;
  
  /// Overwrites the [i]-th element of the array at [ptr] with [value].
  void Function(Pointer<T> ptr, int i, T value) indexSetterFunc;

  RTempStructAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.castFunc,
    required this.sizeOfFunc,
    required this.writeIntoIndexedFunc,
    required this.writeIntoFunc,
    required this.setCFunc,
    required this.indexerFunc,
    required this.indexSetterFunc,
  });

  @override
  String signature() => '$runtimeType<$T, $X>';

  /// Returns the total byte size for [count] structs.
  int Size([int count = 1]) => count*sizeOfFunc();

  /// Allocates an unslotted block of [count] structs.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<T> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted array and writes each [X] value from [array] into it.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<T> RawArray(List<X> array) {
    final p = Raw(array.length);
    for (int i = 0; i < array.length; i++) writeIntoIndexedFunc(p, i, array[i]);
    return p;
  }

  /// Allocates an unslotted array of [count] structs, populating each via
  /// `init(i, struct)` which writes directly into the native memory.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<T> RawFillInto(int count, void Function(int, T) init) {
    final p = Raw(count);
    for (int i = 0; i < count; i++) init(i, indexerFunc(p, i));
    return p;
  }

  /// Allocates an unslotted array of [count] structs, setting each element to
  /// the [T] returned by `init(ptr, i)`.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<T> RawFillWith(int count, T Function(Pointer<T>, int) init) {
    final p = Raw(count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(p, i));
    return p;
  }

  /// Copies [length] structs from [src] into a tracked slot using [setCFunc].
  Pointer<T> Copy(Pointer<T> src, int length, {String? key}) {
    final p = At(_slotKey(key), length);
    for (int i = 0; i < length; i++) setCFunc(p, i, indexerFunc(src, i));
    return p;
  }

  /// Returns the pointer for slot [key], optionally writing [value] into it.
  ///
  /// Allocates the slot on first use.
  Pointer<T> Value([X? value, String? key]) {
    final p = At(_slotKey(key));
    if (value != null) writeIntoFunc(p, value);
    return p;
  }

  /// Writes [array] into a tracked slot of sufficient capacity.
  Pointer<T> Array(List<X> array, {String? key}) {
    final p = At(_slotKey(key), array.length);
    for (int i = 0; i < array.length; i++) writeIntoIndexedFunc(p, i, array[i]);
    return p;
  }

  /// Fills a tracked slot of [count] structs, producing each element via
  /// `init(i)` and writing it through [writeIntoIndexedFunc].
  Pointer<T> Fill(int count, X Function(int) init, {String? key}) {
    final p = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) writeIntoIndexedFunc(p, i, init(i));
    return p;
  }

  /// Fills a tracked slot of [count] structs by calling `init(i, struct)`
  /// which writes directly into the native struct fields.
  Pointer<T> FillInto(int count, void Function(int, T) init, {String? key}) {
    final p = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) init(i, indexerFunc(p, i));
    return p;
  }

  /// Fills a tracked slot of [count] structs by setting each element to the
  /// [T] returned by `init(ptr, i)`.
  Pointer<T> FillWith(int count, T Function(Pointer<T>, int) init, {String? key}) {
    final p = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) indexSetterFunc(p, i, init(p, i));
    return p;
  }

  /// Converts [value] to its C representation into a tracked slot, or returns
  /// an existing slot if [value] is `null`.
  ///
  /// The slot key defaults to `'default'`. Equivalent to calling
  /// `value.toC(temp, key)` directly.
  Pointer<T> ToC([X? value, String? key]) {
    key = _slotKey(key);
    return value?.toC(_temp, key) ?? At(key);
  }
}

/// A slot-based allocator for arrays of **pointers** to native structs of type [T].
///
/// Manages `Pointer<Pointer<T>>` slots where each inner `Pointer<T>` is
/// produced from a `List<X>` via [rawArrayFunc].
class RTempStructPtrAlloc<T extends Struct, X extends StructD<X, T>> extends RTempAlloc<Pointer<T>> {

  /// Converts an `X` of Dart struct wrapper into an allocated `Pointer<T>` pointer.
  Pointer<T> Function([X?, String?]) valueFunc;

  /// Converts a `List<X>` of Dart struct wrappers into an allocated `Pointer<T>` array.
  Pointer<T> Function(List<X> array) rawArrayFunc;

  /// Overwrites the [i]-th element of the array at [ptr] with [value].
  void Function(Pointer<Pointer<T>> ptr, int i, Pointer<T> value) indexSetterFunc;

  RTempStructPtrAlloc(super.temp, super.name, {
    required super.allocatorFunc,
    required super.printerFunc,
    required this.valueFunc,
    required this.rawArrayFunc,
    required this.indexSetterFunc,
  });

  @override
  String signature() => '$runtimeType<$T, $X>';

  /// Allocates an unslotted `Pointer<Pointer<T>>` of [count] elements.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<T>> Raw([int count = 1]) => allocatorFunc(count);

  /// Allocates an unslotted pointer-of-pointers from a list of struct arrays.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<T>> RawArray(List<List<X>> arrays) {
    final p = Raw(arrays.length);
    for (int i = 0; i < arrays.length; i++) p[i] = rawArrayFunc(arrays[i]);
    return p;
  }

  /// Writes [array] into a tracked slot of sufficient capacity.
  Pointer<Pointer<T>> Array(List<X> array, {String? key}) {
    final slotKey = _slotKey(key);
    final p = At(slotKey, array.length);
    for (int i = 0; i < array.length; i++) indexSetterFunc(p, i, valueFunc(array[i], '${slotKey}_$i'));
    return p;
  }

  /// Writes each sub-array in [arrays] into a tracked slot and returns the
  /// outer `Pointer<Pointer<T>>]`
  Pointer<Pointer<T>> Fill(List<List<X>> arrays, {String? key}) {
    final p = At(_slotKey(key), arrays.length);
    for (int i = 0; i < arrays.length; i++) p[i] = rawArrayFunc(arrays[i]);
    return p;
  }

  /// Fills a tracked slot of [count] pointers by calling `init(i)` for each index.
  Pointer<Pointer<T>> FillRaw(int count, Pointer<T> Function(int) init, {String? key}) {
    final pp = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }
}

/// A specialised slot-based allocator for C strings ([Pointer\<Char>]).
///
/// Maintains two separate pools:
/// - **Anonymous slots** – a ring buffer of [slotCount] slots, cycled through
///   via [Value] without a key. Useful for transient strings within a single
///   frame.
/// - **Keyed slots** – named slots allocated on demand via [ValueAt] and
///   [Array], persisting until explicitly freed or [_dispose] is called.
///
/// String memory is managed with [malloc] and is grown in-place when the
/// encoded UTF-8 length of a new string exceeds the current slot capacity,
/// avoiding unnecessary reallocations for strings of similar length.
final class RTempStringAlloc extends RTempAlloc<Pointer<Char>> {

  /// Number of anonymous (ring-buffer) string slots pre-reserved on construction.
  final int slotCount;

  RTempStringAlloc(super.temp, super.name, {
    required this.slotCount,
    required super.allocatorFunc,
    required super.printerFunc,
  }) { _reset(); }

  final Map<String, int> _StringSlotsKeyed = {};
  List<Pointer<Char>> _StringSlots = [];
  List<int> _StringCapacities = [];
  int _StringAnonIndex = 0;

  /// Resets all slot bookkeeping structures to their initial state.
  ///
  /// Called during construction and at the end of [_dispose].
  void _reset() {
    // NOTE: needs to be growable
    _StringSlots = .filled(slotCount, nullptr, growable: true);
    _StringCapacities = .filled(slotCount, 0, growable: true);
    _StringAnonIndex = 0;
  }

  /// Allocates and returns an unslotted array of [count] `Pointer<Char>` pointers.
  ///
  /// The caller is responsible for freeing the returned pointer.
  Pointer<Pointer<Char>> Raw([int count = 1]) => allocatorFunc(count);

  /// Writes each string in [array] into keyed sub-slots and returns a tracked
  /// `Pointer<Pointer<Char>>` of length `array.length`.
  ///
  /// Sub-slot keys follow the pattern `'<key>_<i>'`. [key] defaults to
  /// `'default'`.
  Pointer<Pointer<Char>> Array(List<String> array, {String? key}) {
    final arrayKey = _slotKey(key);
    final pp = At(arrayKey, array.length);
    for (int i = 0; i < array.length; i++) pp[i] = ValueAt('${arrayKey}_$i', array[i]);
    return pp;
  }

  /// Fills a tracked [Pointer<Pointer<Char>>] of [count] elements by calling
  /// [init](i) for each index.
  Pointer<Pointer<Char>> Fill(int count, Pointer<Char> Function(int) init, {String? key}) {
    final pp = At(_slotKey(key), count);
    for (int i = 0; i < count; i++) pp[i] = init(i);
    return pp;
  }

  /// Returns a `Pointer<Char>` for [text] using the next anonymous ring-buffer slot.
  /// 
  /// Anonymous slots cycle modulo [slotCount], so older anonymous strings may be overwritten.
  /// 
  /// If [key] is provided, delegates to [ValueAt] instead.
  Pointer<Char> Value(String text, [String? key]) {
    if (key != null) return ValueAt(key, text);
    final slot = _StringAnonIndex;
    _StringAnonIndex = (_StringAnonIndex + 1) % slotCount;
    _ensureStringSlotExists(slot);
    return _writeStringToSlot(slot, text);
  }

  /// Returns the `Pointer<Char>` for the keyed slot [key], optionally writing
  /// [text] into it.
  ///
  /// Allocates the slot on first use. If [text] is `null` the existing string
  /// is returned; asserts that the slot has been initialised at least once.
  Pointer<Char> ValueAt(String key, [String? text]) {
    final slot = _StringSlotsKeyed.putIfAbsent(
      key, () => _StringSlots.length
    );

    _ensureStringSlotExists(slot);

    if (text != null) {
      return _writeStringToSlot(slot, text);
    }

    assert(
      _StringSlots[slot] != nullptr,
      '[TEMP] String.ValueAt("$key") used before initialization'
    );

    return _StringSlots[slot];
  }

  /// Ensures the slot list is large enough to hold index [slot], growing it
  /// with null-pointer sentinels if necessary.
  void _ensureStringSlotExists(int slot) {
    if (slot < _StringSlots.length) return;

    final growBy = slot + 1 - _StringSlots.length;

    _StringSlots.addAll(List.filled(growBy, nullptr));
    _StringCapacities.addAll(List.filled(growBy, 0));
  }

  /// Writes [text] into slot [slot], reallocating if the current capacity is
  /// insufficient for the UTF-8 encoded length.
  ///
  /// Always null-terminates the written string.
  Pointer<Char> _writeStringToSlot(int slot, String text) {
    final encoded = utf8.encode(text);
    final requiredBytes = encoded.length + 1;

    if (
      _StringSlots[slot] == nullptr ||
      _StringCapacities[slot] < requiredBytes
    ) {
      if (_StringSlots[slot] != nullptr) {
        malloc.free(_StringSlots[slot]);
      }

      _StringSlots[slot] = malloc.allocate<Char>(requiredBytes);
      _StringCapacities[slot] = requiredBytes;
    }

    final dst = _StringSlots[slot]
      .cast<Uint8>()
      .asTypedList(requiredBytes);

    dst.setAll(0, encoded);
    dst[encoded.length] = 0;

    return _StringSlots[slot];
  }

  @override
  void Free(String key) {
    if (!_StringSlotsKeyed.containsKey(key)) {
      throw StateError('[FREE] Cannot free unallocated String slot $key');
    }

    int slot = _StringSlotsKeyed[key]!;
    calloc.free(_StringSlots[slot]);
    _StringSlotsKeyed.remove(key);
    _StringSlots.removeAt(slot);
    _StringCapacities.removeAt(slot);
  }

  @override
  void _dispose() {
    if (_StringSlots.isNotEmpty) {
      final nonNulls = _StringSlots.where((e) => e != nullptr);
      _temp.debugFreeInfo('Freeing preallocated $slotCount $name slots (used ${nonNulls.length})');
      nonNulls.forEach(calloc.free);
    }
    if (_StringSlotsKeyed.isNotEmpty) {
      _temp.debugFreeInfo('Freeing user-defined ${_StringSlotsKeyed.length} $name slots');
    }
    _reset();
  }
}

class RaylibTemp extends RaylibModule {
  final RaylibTempOptions options;

  RaylibTemp(super.lib, {
    this.options = const RaylibTempOptions(),
  }) {
    _init();
    _preAllocate();
    _preAllocateReusables();
  }

  bool _enableSyncing = true;
  void enableSyncing(bool sync) => _enableSyncing = sync;
  bool get doSync => _enableSyncing;

  int _currentId = 0;
  int nextId() => _currentId++;

  bool _debugFreeEnabled = false;
  void debugFree(bool v) => _debugFreeEnabled = v;

  bool _debugSyncEnabled = false;
  void debugSync(bool v) => _debugSyncEnabled = v;

  late Map<String, RTempAlloc> _allocators;

  void debugFreeInfo(String message) { if (_debugFreeEnabled) logInfo(message); }
  void debugSyncInfo(String message) { if (_debugSyncEnabled) logInfo(message); }

  late RTempStringAlloc String$;

  late RTempLitAlloc<bool, Bool> Bool$;
  late RTempLitPtrAlloc<bool, Bool> Ptr$Bool$;
  late RTempLitTypedFloatListAlloc<num, Float> Float$;
  late RTempLitPtrAlloc<num, Float> Ptr$Float$;
  late RTempLitTypedIntListAlloc<num, Int> Int$;
  late RTempLitPtrAlloc<num, Int> Ptr$Int$;
  late RTempLitTypedIntListAlloc<num, UnsignedInt> UInt$;
  late RTempLitPtrAlloc<num, UnsignedInt> Ptr$UInt$;
  late RTempLitTypedIntListAlloc<num, Int8> Int8$;
  late RTempLitPtrAlloc<num, Int8> Ptr$Int8$;
  late RTempLitTypedIntListAlloc<num, Uint8> UInt8$;
  late RTempLitPtrAlloc<num, Uint8> Ptr$UInt8$;
  late RTempLitTypedIntListAlloc<num, Int16> Int16$;
  late RTempLitPtrAlloc<num, Int16> Ptr$Int16$;
  late RTempLitTypedIntListAlloc<num, Uint16> UInt16$;
  late RTempLitPtrAlloc<num, Uint16> Ptr$UInt16$;
  late RTempLitTypedIntListAlloc<num, Int32> Int32$;
  late RTempLitPtrAlloc<num, Int32> Ptr$Int32$;
  late RTempLitTypedIntListAlloc<num, Uint32> UInt32$;
  late RTempLitPtrAlloc<num, Uint32> Ptr$UInt32$;
  late RTempLitTypedIntListAlloc<num, Int64> Int64$;
  late RTempLitPtrAlloc<num, Int64> Ptr$Int64$;
  late RTempLitTypedIntListAlloc<num, Uint64> UInt64$;
  late RTempLitPtrAlloc<num, Uint64> Ptr$UInt64$;
  late RTempLitTypedIntListAlloc<num, Char> Char$;
  late RTempLitPtrAlloc<num, Char> Ptr$Char$;
  late RTempLitTypedIntListAlloc<num, UnsignedChar> UChar$;
  late RTempLitPtrAlloc<num, UnsignedChar> Ptr$UChar$;
  late RTempLitTypedIntListAlloc<num, UnsignedShort> UShort$;
  late RTempLitPtrAlloc<num, UnsignedShort> Ptr$UShort$;
  late RTempLitTypedIntListAlloc<num, Short> Short$;
  late RTempLitPtrAlloc<num, Short> Ptr$Short$;
  late RTempStructAlloc<AutomationEventListC, AutomationEventListD> AutomationEventList$;
  late RTempStructPtrAlloc<AutomationEventListC, AutomationEventListD> Ptr$AutomationEventList$;
  late RTempStructAlloc<AutomationEventC, AutomationEventD> AutomationEvent$;
  late RTempStructPtrAlloc<AutomationEventC, AutomationEventD> Ptr$AutomationEvent$;
  late RTempStructAlloc<AudioStreamC, AudioStreamD> AudioStream$;
  late RTempStructPtrAlloc<AudioStreamC, AudioStreamD> Ptr$AudioStream$;
  late RTempStructAlloc<BoneInfoC, BoneInfoD> BoneInfo$;
  late RTempStructPtrAlloc<BoneInfoC, BoneInfoD> Ptr$BoneInfo$;
  late RTempStructAlloc<BoundingBoxC, BoundingBoxD> BoundingBox$;
  late RTempStructPtrAlloc<BoundingBoxC, BoundingBoxD> Ptr$BoundingBox$;
  late RTempStructAlloc<Camera2DC, Camera2DD> Camera2D$;
  late RTempStructPtrAlloc<Camera2DC, Camera2DD> Ptr$Camera2D$;
  late RTempStructAlloc<Camera3DC, Camera3DD> Camera3D$;
  late RTempStructPtrAlloc<Camera3DC, Camera3DD> Ptr$Camera3D$;
  late RTempStructAlloc<ColorC, ColorD> Color$;
  late RTempStructPtrAlloc<ColorC, ColorD> Ptr$Color$;
  late RTempStructAlloc<FilePathListC, FilePathListD> FilePathList$;
  late RTempStructPtrAlloc<FilePathListC, FilePathListD> Ptr$FilePathList$;
  late RTempStructAlloc<FontC, FontD> Font$;
  late RTempStructPtrAlloc<FontC, FontD> Ptr$Font$;
  late RTempStructAlloc<GlyphInfoC, GlyphInfoD> GlyphInfo$;
  late RTempStructPtrAlloc<GlyphInfoC, GlyphInfoD> Ptr$GlyphInfo$;
  late RTempStructAlloc<ImageC, ImageD> Image$;
  late RTempStructPtrAlloc<ImageC, ImageD> Ptr$Image$;
  late RTempStructAlloc<LightC, LightD> Light$;
  late RTempStructPtrAlloc<LightC, LightD> Ptr$Light$;
  late RTempStructAlloc<MaterialC, MaterialD> Material$;
  late RTempStructPtrAlloc<MaterialC, MaterialD> Ptr$Material$;
  late RTempStructAlloc<MaterialMapC, MaterialMapD> MaterialMap$;
  late RTempStructPtrAlloc<MaterialMapC, MaterialMapD> Ptr$MaterialMap$;
  late RTempStructAlloc<MatrixC, MatrixD> Matrix$;
  late RTempStructPtrAlloc<MatrixC, MatrixD> Ptr$Matrix$;
  late RTempStructAlloc<MeshC, MeshD> Mesh$;
  late RTempStructPtrAlloc<MeshC, MeshD> Ptr$Mesh$;
  late RTempStructAlloc<ModelC, ModelD> Model$;
  late RTempStructPtrAlloc<ModelC, ModelD> Ptr$Model$;
  late RTempStructAlloc<ModelAnimationC, ModelAnimationD> ModelAnimation$;
  late RTempStructPtrAlloc<ModelAnimationC, ModelAnimationD> Ptr$ModelAnimation$;
  late RTempStructAlloc<MusicC, MusicD> Music$;
  late RTempStructPtrAlloc<MusicC, MusicD> Ptr$Music$;
  late RTempStructAlloc<NPatchInfoC, NPatchInfoD> NPatchInfo$;
  late RTempStructPtrAlloc<NPatchInfoC, NPatchInfoD> Ptr$NPatchInfo$;
  late RTempStructAlloc<RectangleC, RectangleD> Rectangle$;
  late RTempStructPtrAlloc<RectangleC, RectangleD> Ptr$Rectangle$;
  late RTempStructAlloc<RlDrawCallC, RlDrawCallD> RlDrawCall$;
  late RTempStructPtrAlloc<RlDrawCallC, RlDrawCallD> Ptr$RlDrawCall$;
  late RTempStructAlloc<RlRenderBatchC, RlRenderBatchD> RlRenderBatch$;
  late RTempStructPtrAlloc<RlRenderBatchC, RlRenderBatchD> Ptr$RlRenderBatch$;
  late RTempStructAlloc<RlVertexBufferC, RlVertexBufferD> RlVertexBuffer$;
  late RTempStructPtrAlloc<RlVertexBufferC, RlVertexBufferD> Ptr$RlVertexBuffer$;
  late RTempStructAlloc<RayC, RayD> Ray$;
  late RTempStructPtrAlloc<RayC, RayD> Ptr$Ray$;
  late RTempStructAlloc<RayCollisionC, RayCollisionD> RayCollision$;
  late RTempStructPtrAlloc<RayCollisionC, RayCollisionD> Ptr$RayCollision$;
  late RTempStructAlloc<RenderTextureC, RenderTextureD> RenderTexture$;
  late RTempStructPtrAlloc<RenderTextureC, RenderTextureD> Ptr$RenderTexture$;
  late RTempStructAlloc<ShaderC, ShaderD> Shader$;
  late RTempStructPtrAlloc<ShaderC, ShaderD> Ptr$Shader$;
  late RTempStructAlloc<SoundC, SoundD> Sound$;
  late RTempStructPtrAlloc<SoundC, SoundD> Ptr$Sound$;
  late RTempStructAlloc<TextureC, TextureD> Texture$;
  late RTempStructPtrAlloc<TextureC, TextureD> Ptr$Texture$;
  late RTempStructAlloc<TransformC, TransformD> Transform$;
  late RTempStructPtrAlloc<TransformC, TransformD> Ptr$Transform$;
  late RTempStructAlloc<Vector2C, Vector2D> Vector2$;
  late RTempStructPtrAlloc<Vector2C, Vector2D> Ptr$Vector2$;
  late RTempStructAlloc<Vector3C, Vector3D> Vector3$;
  late RTempStructPtrAlloc<Vector3C, Vector3D> Ptr$Vector3$;
  late RTempStructAlloc<Vector4C, Vector4D> Vector4$;
  late RTempStructPtrAlloc<Vector4C, Vector4D> Ptr$Vector4$;
  late RTempStructAlloc<VrDeviceInfoC, VrDeviceInfoD> VrDeviceInfo$;
  late RTempStructPtrAlloc<VrDeviceInfoC, VrDeviceInfoD> Ptr$VrDeviceInfo$;
  late RTempStructAlloc<VrStereoConfigC, VrStereoConfigD> VrStereoConfig$;
  late RTempStructPtrAlloc<VrStereoConfigC, VrStereoConfigD> Ptr$VrStereoConfig$;
  late RTempStructAlloc<WaveC, WaveD> Wave$;
  late RTempStructPtrAlloc<WaveC, WaveD> Ptr$Wave$;

  /// ===========================
  /// ====== CUSTOM ALLOCS ======
  /// ===========================

  final Map<String, RTempAlloc> _customAllocators = {};
  
  void registerAllocator(String key, RTempAlloc alloc) {
    if (_customAllocators.containsKey(key)) {
      final sig = _customAllocators[key]!.signature();
      throw StateError("Allocator '$key' ('$sig') already exists!");
    }

    _customAllocators[key] = alloc;
  }

  RTempAlloc _getCustomAllocatorOrThrow(String key) {
    final alloc = _customAllocators[key];
    if (alloc == null) throw StateError("No custom allocator registered for '$key'!");
    return alloc;
  }

  T alloc<T extends RTempAlloc>(String key) => _customAllocators[key] as T;

  RTempLitAlloc<X, T> allocLit<X, T extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitAlloc<X, T>;

  RTempLitTypedIntListAlloc<X, T> allocIntList<X, T extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitTypedIntListAlloc<X, T>;

  RTempLitTypedFloatListAlloc<X, T> allocFloatList<X, T extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitTypedFloatListAlloc<X, T>;

  RTempLitPtrAlloc<X, T> allocLitPtr<X, T extends NativeType>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempLitPtrAlloc<X, T>;

  RTempStructAlloc<T, X> allocStruct<T extends Struct, X extends StructD<X, T>>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempStructAlloc<T, X>;

  RTempStructPtrAlloc<T, X> allocStructPtr<T extends Struct, X extends StructD<X, T>>(String key) =>
    _getCustomAllocatorOrThrow(key) as RTempStructPtrAlloc<T, X>;

  /// ============================
  /// ====== INITIALIZATION ======
  /// ============================

  void _init() {
    if (options.stringCount > 0) {
      logInfo('[TEMP] Allocating ${options.stringCount} String slots');
    }

    String$ = .new(this, 'String\$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Char>>(count),
      printerFunc: (ptr) => ptr.value.toD,
      slotCount: options.stringCount,
    );

    Bool$ = .new(this, r'Bool$',
      allocatorFunc: ([count = 1]) => calloc<Bool>(count),
      castFunc: (ptr) => ptr.cast<Bool>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
      literalSetterFunc: (ptr, value) => ptr.value = value,
      sizeOfFunc: () => sizeOf<Bool>(),
      printerFunc: (ptr) => ptr.value.toString(),
    );

    Ptr$Bool$ = .new(this, r'Ptr$Bool$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Bool>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Bool>> at this level',
      rawArrayFunc: Bool$.RawArray,
    );

    Float$ = .new(this, r'Float$',
      allocatorFunc: ([count = 1]) => calloc<Float>(count),
      castFunc: (ptr) => ptr.cast<Float>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toDouble(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toDouble(),
      sizeOfFunc: () => sizeOf<Float>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => Float$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Float$ = .new(this, r'Ptr$Float$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Float>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Float>> at this level',
      rawArrayFunc: Float$.RawArray,
    );

    Int$ = .new(this, r'Int$',
      allocatorFunc: ([count = 1]) => calloc<Int>(count),
      castFunc: (ptr) => ptr.cast<Int>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Int>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Int32>().asTypedList(length),
      asDartList: (ptr, length) => Int$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Int$ = .new(this, r'Ptr$Int$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Int>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Int>> at this level',
      rawArrayFunc: Int$.RawArray,
    );

    UInt$ = .new(this, r'UInt$',
      allocatorFunc: ([count = 1]) => calloc<UnsignedInt>(count),
      castFunc: (ptr) => ptr.cast<UnsignedInt>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<UnsignedInt>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Uint32>().asTypedList(length),
      asDartList: (ptr, length) => UInt$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UInt$ = .new(this, r'Ptr$UInt$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<UnsignedInt>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<UnsignedInt>> at this level',
      rawArrayFunc: UInt$.RawArray,
    );

    Int8$ = .new(this, r'Int8$',
      allocatorFunc: ([count = 1]) => calloc<Int8>(count),
      castFunc: (ptr) => ptr.cast<Int8>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Int8>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => Int8$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Int8$ = .new(this, r'Ptr$Int8$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Int8>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Int8>> at this level',
      rawArrayFunc: Int8$.RawArray,
    );

    UInt8$ = .new(this, r'UInt8$',
      allocatorFunc: ([count = 1]) => calloc<Uint8>(count),
      castFunc: (ptr) => ptr.cast<Uint8>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Uint8>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => UInt8$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UInt8$ = .new(this, r'Ptr$UInt8$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Uint8>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Uint8>> at this level',
      rawArrayFunc: UInt8$.RawArray,
    );

    Int16$ = .new(this, r'Int16$',
      allocatorFunc: ([count = 1]) => calloc<Int16>(count),
      castFunc: (ptr) => ptr.cast<Int16>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Int16>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => Int16$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Int16$ = .new(this, r'Ptr$Int16$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Int16>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Int16>> at this level',
      rawArrayFunc: Int16$.RawArray,
    );

    UInt16$ = .new(this, r'UInt16$',
      allocatorFunc: ([count = 1]) => calloc<Uint16>(count),
      castFunc: (ptr) => ptr.cast<Uint16>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Uint16>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => UInt16$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UInt16$ = .new(this, r'Ptr$UInt16$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Uint16>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Uint16>> at this level',
      rawArrayFunc: UInt16$.RawArray,
    );

    Int32$ = .new(this, r'Int32$',
      allocatorFunc: ([count = 1]) => calloc<Int32>(count),
      castFunc: (ptr) => ptr.cast<Int32>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Int32>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => Int32$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Int32$ = .new(this, r'Ptr$Int32$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Int32>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Int32>> at this level',
      rawArrayFunc: Int32$.RawArray,
    );

    UInt32$ = .new(this, r'UInt32$',
      allocatorFunc: ([count = 1]) => calloc<Uint32>(count),
      castFunc: (ptr) => ptr.cast<Uint32>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Uint32>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => UInt32$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UInt32$ = .new(this, r'Ptr$UInt32$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Uint32>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Uint32>> at this level',
      rawArrayFunc: UInt32$.RawArray,
    );

    Int64$ = .new(this, r'Int64$',
      allocatorFunc: ([count = 1]) => calloc<Int64>(count),
      castFunc: (ptr) => ptr.cast<Int64>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Int64>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => Int64$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Int64$ = .new(this, r'Ptr$Int64$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Int64>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Int64>> at this level',
      rawArrayFunc: Int64$.RawArray,
    );

    UInt64$ = .new(this, r'UInt64$',
      allocatorFunc: ([count = 1]) => calloc<Uint64>(count),
      castFunc: (ptr) => ptr.cast<Uint64>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Uint64>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.asTypedList(length),
      asDartList: (ptr, length) => UInt64$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UInt64$ = .new(this, r'Ptr$UInt64$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Uint64>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Uint64>> at this level',
      rawArrayFunc: UInt64$.RawArray,
    );

    Char$ = .new(this, r'Char$',
      allocatorFunc: ([count = 1]) => calloc<Char>(count),
      castFunc: (ptr) => ptr.cast<Char>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Char>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Int8>().asTypedList(length),
      asDartList: (ptr, length) => Char$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Char$ = .new(this, r'Ptr$Char$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Char>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Char>> at this level',
      rawArrayFunc: Char$.RawArray,
    );

    UChar$ = .new(this, r'UChar$',
      allocatorFunc: ([count = 1]) => calloc<UnsignedChar>(count),
      castFunc: (ptr) => ptr.cast<UnsignedChar>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<UnsignedChar>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Uint8>().asTypedList(length),
      asDartList: (ptr, length) => UChar$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UChar$ = .new(this, r'Ptr$UChar$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<UnsignedChar>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<UnsignedChar>> at this level',
      rawArrayFunc: UChar$.RawArray,
    );

    UShort$ = .new(this, r'UShort$',
      allocatorFunc: ([count = 1]) => calloc<UnsignedShort>(count),
      castFunc: (ptr) => ptr.cast<UnsignedShort>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<UnsignedShort>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Uint16>().asTypedList(length),
      asDartList: (ptr, length) => UShort$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$UShort$ = .new(this, r'Ptr$UShort$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<UnsignedShort>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<UnsignedShort>> at this level',
      rawArrayFunc: UShort$.RawArray,
    );

    Short$ = .new(this, r'Short$',
      allocatorFunc: ([count = 1]) => calloc<Short>(count),
      castFunc: (ptr) => ptr.cast<Short>(),
      indexSetterFunc: (ptr, i, value) => ptr[i] = value.toInt(),
      literalSetterFunc: (ptr, value) => ptr.value = value.toInt(),
      sizeOfFunc: () => sizeOf<Short>(),
      printerFunc: (ptr) => ptr.value.toString(),
      asTypedList: (ptr, length) => ptr.cast<Int16>().asTypedList(length),
      asDartList: (ptr, length) => Short$.asTypedList(ptr, length).toList().cast(),
    );

    Ptr$Short$ = .new(this, r'Ptr$Short$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Short>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Short>> at this level',
      rawArrayFunc: Short$.RawArray,
    );

    AutomationEventList$ = .new(this, r'AutomationEventList$',
      allocatorFunc: ([count = 1]) => calloc<AutomationEventListC>(count),
      castFunc: (ptr) => ptr.cast<AutomationEventListC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<AutomationEventListC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$AutomationEventList$ = .new(this, r'Ptr$AutomationEventList$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<AutomationEventListC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<AutomationEventListC>> at this level',
      valueFunc: AutomationEventList$.Value,
      rawArrayFunc: AutomationEventList$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    AutomationEvent$ = .new(this, r'AutomationEvent$',
      allocatorFunc: ([count = 1]) => calloc<AutomationEventC>(count),
      castFunc: (ptr) => ptr.cast<AutomationEventC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<AutomationEventC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$AutomationEvent$ = .new(this, r'Ptr$AutomationEvent$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<AutomationEventC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<AutomationEventC>> at this level',
      valueFunc: AutomationEvent$.Value,
      rawArrayFunc: AutomationEvent$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    AudioStream$ = .new(this, r'AudioStream$',
      allocatorFunc: ([count = 1]) => calloc<AudioStreamC>(count),
      castFunc: (ptr) => ptr.cast<AudioStreamC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<AudioStreamC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$AudioStream$ = .new(this, r'Ptr$AudioStream$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<AudioStreamC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<AudioStreamC>> at this level',
      valueFunc: AudioStream$.Value,
      rawArrayFunc: AudioStream$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    BoneInfo$ = .new(this, r'BoneInfo$',
      allocatorFunc: ([count = 1]) => calloc<BoneInfoC>(count),
      castFunc: (ptr) => ptr.cast<BoneInfoC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<BoneInfoC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$BoneInfo$ = .new(this, r'Ptr$BoneInfo$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<BoneInfoC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<BoneInfoC>> at this level',
      valueFunc: BoneInfo$.Value,
      rawArrayFunc: BoneInfo$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    BoundingBox$ = .new(this, r'BoundingBox$',
      allocatorFunc: ([count = 1]) => calloc<BoundingBoxC>(count),
      castFunc: (ptr) => ptr.cast<BoundingBoxC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<BoundingBoxC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$BoundingBox$ = .new(this, r'Ptr$BoundingBox$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<BoundingBoxC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<BoundingBoxC>> at this level',
      valueFunc: BoundingBox$.Value,
      rawArrayFunc: BoundingBox$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Camera2D$ = .new(this, r'Camera2D$',
      allocatorFunc: ([count = 1]) => calloc<Camera2DC>(count),
      castFunc: (ptr) => ptr.cast<Camera2DC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<Camera2DC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Camera2D$ = .new(this, r'Ptr$Camera2D$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Camera2DC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Camera2DC>> at this level',
      valueFunc: Camera2D$.Value,
      rawArrayFunc: Camera2D$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Camera3D$ = .new(this, r'Camera3D$',
      allocatorFunc: ([count = 1]) => calloc<Camera3DC>(count),
      castFunc: (ptr) => ptr.cast<Camera3DC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<Camera3DC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Camera3D$ = .new(this, r'Ptr$Camera3D$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Camera3DC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Camera3DC>> at this level',
      valueFunc: Camera3D$.Value,
      rawArrayFunc: Camera3D$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Color$ = .new(this, r'Color$',
      allocatorFunc: ([count = 1]) => calloc<ColorC>(count),
      castFunc: (ptr) => ptr.cast<ColorC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<ColorC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Color$ = .new(this, r'Ptr$Color$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<ColorC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<ColorC>> at this level',
      valueFunc: Color$.Value,
      rawArrayFunc: Color$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    FilePathList$ = .new(this, r'FilePathList$',
      allocatorFunc: ([count = 1]) => calloc<FilePathListC>(count),
      castFunc: (ptr) => ptr.cast<FilePathListC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<FilePathListC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$FilePathList$ = .new(this, r'Ptr$FilePathList$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<FilePathListC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<FilePathListC>> at this level',
      valueFunc: FilePathList$.Value,
      rawArrayFunc: FilePathList$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Font$ = .new(this, r'Font$',
      allocatorFunc: ([count = 1]) => calloc<FontC>(count),
      castFunc: (ptr) => ptr.cast<FontC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<FontC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Font$ = .new(this, r'Ptr$Font$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<FontC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<FontC>> at this level',
      valueFunc: Font$.Value,
      rawArrayFunc: Font$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    GlyphInfo$ = .new(this, r'GlyphInfo$',
      allocatorFunc: ([count = 1]) => calloc<GlyphInfoC>(count),
      castFunc: (ptr) => ptr.cast<GlyphInfoC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<GlyphInfoC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$GlyphInfo$ = .new(this, r'Ptr$GlyphInfo$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<GlyphInfoC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<GlyphInfoC>> at this level',
      valueFunc: GlyphInfo$.Value,
      rawArrayFunc: GlyphInfo$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Image$ = .new(this, r'Image$',
      allocatorFunc: ([count = 1]) => calloc<ImageC>(count),
      castFunc: (ptr) => ptr.cast<ImageC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<ImageC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Image$ = .new(this, r'Ptr$Image$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<ImageC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<ImageC>> at this level',
      valueFunc: Image$.Value,
      rawArrayFunc: Image$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Light$ = .new(this, r'Light$',
      allocatorFunc: ([count = 1]) => calloc<LightC>(count),
      castFunc: (ptr) => ptr.cast<LightC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<LightC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Light$ = .new(this, r'Ptr$Light$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<LightC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<LightC>> at this level',
      valueFunc: Light$.Value,
      rawArrayFunc: Light$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Material$ = .new(this, r'Material$',
      allocatorFunc: ([count = 1]) => calloc<MaterialC>(count),
      castFunc: (ptr) => ptr.cast<MaterialC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<MaterialC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Material$ = .new(this, r'Ptr$Material$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<MaterialC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<MaterialC>> at this level',
      valueFunc: Material$.Value,
      rawArrayFunc: Material$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    MaterialMap$ = .new(this, r'MaterialMap$',
      allocatorFunc: ([count = 1]) => calloc<MaterialMapC>(count),
      castFunc: (ptr) => ptr.cast<MaterialMapC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<MaterialMapC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$MaterialMap$ = .new(this, r'Ptr$MaterialMap$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<MaterialMapC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<MaterialMapC>> at this level',
      valueFunc: MaterialMap$.Value,
      rawArrayFunc: MaterialMap$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Matrix$ = .new(this, r'Matrix$',
      allocatorFunc: ([count = 1]) => calloc<MatrixC>(count),
      castFunc: (ptr) => ptr.cast<MatrixC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<MatrixC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Matrix$ = .new(this, r'Ptr$Matrix$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<MatrixC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<MatrixC>> at this level',
      valueFunc: Matrix$.Value,
      rawArrayFunc: Matrix$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Mesh$ = .new(this, r'Mesh$',
      allocatorFunc: ([count = 1]) => calloc<MeshC>(count),
      castFunc: (ptr) => ptr.cast<MeshC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<MeshC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Mesh$ = .new(this, r'Ptr$Mesh$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<MeshC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<MeshC>> at this level',
      valueFunc: Mesh$.Value,
      rawArrayFunc: Mesh$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Model$ = .new(this, r'Model$',
      allocatorFunc: ([count = 1]) => calloc<ModelC>(count),
      castFunc: (ptr) => ptr.cast<ModelC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<ModelC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Model$ = .new(this, r'Ptr$Model$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<ModelC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<ModelC>> at this level',
      valueFunc: Model$.Value,
      rawArrayFunc: Model$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    ModelAnimation$ = .new(this, r'ModelAnimation$',
      allocatorFunc: ([count = 1]) => calloc<ModelAnimationC>(count),
      castFunc: (ptr) => ptr.cast<ModelAnimationC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<ModelAnimationC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$ModelAnimation$ = .new(this, r'Ptr$ModelAnimation$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<ModelAnimationC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<ModelAnimationC>> at this level',
      valueFunc: ModelAnimation$.Value,
      rawArrayFunc: ModelAnimation$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Music$ = .new(this, r'Music$',
      allocatorFunc: ([count = 1]) => calloc<MusicC>(count),
      castFunc: (ptr) => ptr.cast<MusicC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<MusicC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Music$ = .new(this, r'Ptr$Music$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<MusicC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<MusicC>> at this level',
      valueFunc: Music$.Value,
      rawArrayFunc: Music$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    NPatchInfo$ = .new(this, r'NPatchInfo$',
      allocatorFunc: ([count = 1]) => calloc<NPatchInfoC>(count),
      castFunc: (ptr) => ptr.cast<NPatchInfoC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<NPatchInfoC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$NPatchInfo$ = .new(this, r'Ptr$NPatchInfo$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<NPatchInfoC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<NPatchInfoC>> at this level',
      valueFunc: NPatchInfo$.Value,
      rawArrayFunc: NPatchInfo$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Rectangle$ = .new(this, r'Rectangle$',
      allocatorFunc: ([count = 1]) => calloc<RectangleC>(count),
      castFunc: (ptr) => ptr.cast<RectangleC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RectangleC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Rectangle$ = .new(this, r'Ptr$Rectangle$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RectangleC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RectangleC>> at this level',
      valueFunc: Rectangle$.Value,
      rawArrayFunc: Rectangle$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    RlDrawCall$ = .new(this, r'RlDrawCall$',
      allocatorFunc: ([count = 1]) => calloc<RlDrawCallC>(count),
      castFunc: (ptr) => ptr.cast<RlDrawCallC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RlDrawCallC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$RlDrawCall$ = .new(this, r'Ptr$RlDrawCall$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RlDrawCallC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RlDrawCallC>> at this level',
      valueFunc: RlDrawCall$.Value,
      rawArrayFunc: RlDrawCall$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    RlRenderBatch$ = .new(this, r'RlRenderBatch$',
      allocatorFunc: ([count = 1]) => calloc<RlRenderBatchC>(count),
      castFunc: (ptr) => ptr.cast<RlRenderBatchC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RlRenderBatchC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$RlRenderBatch$ = .new(this, r'Ptr$RlRenderBatch$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RlRenderBatchC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RlRenderBatchC>> at this level',
      valueFunc: RlRenderBatch$.Value,
      rawArrayFunc: RlRenderBatch$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    RlVertexBuffer$ = .new(this, r'RlVertexBuffer$',
      allocatorFunc: ([count = 1]) => calloc<RlVertexBufferC>(count),
      castFunc: (ptr) => ptr.cast<RlVertexBufferC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RlVertexBufferC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$RlVertexBuffer$ = .new(this, r'Ptr$RlVertexBuffer$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RlVertexBufferC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RlVertexBufferC>> at this level',
      valueFunc: RlVertexBuffer$.Value,
      rawArrayFunc: RlVertexBuffer$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Ray$ = .new(this, r'Ray$',
      allocatorFunc: ([count = 1]) => calloc<RayC>(count),
      castFunc: (ptr) => ptr.cast<RayC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RayC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Ray$ = .new(this, r'Ptr$Ray$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RayC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RayC>> at this level',
      valueFunc: Ray$.Value,
      rawArrayFunc: Ray$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    RayCollision$ = .new(this, r'RayCollision$',
      allocatorFunc: ([count = 1]) => calloc<RayCollisionC>(count),
      castFunc: (ptr) => ptr.cast<RayCollisionC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RayCollisionC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$RayCollision$ = .new(this, r'Ptr$RayCollision$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RayCollisionC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RayCollisionC>> at this level',
      valueFunc: RayCollision$.Value,
      rawArrayFunc: RayCollision$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    RenderTexture$ = .new(this, r'RenderTexture$',
      allocatorFunc: ([count = 1]) => calloc<RenderTextureC>(count),
      castFunc: (ptr) => ptr.cast<RenderTextureC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<RenderTextureC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$RenderTexture$ = .new(this, r'Ptr$RenderTexture$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<RenderTextureC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<RenderTextureC>> at this level',
      valueFunc: RenderTexture$.Value,
      rawArrayFunc: RenderTexture$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Shader$ = .new(this, r'Shader$',
      allocatorFunc: ([count = 1]) => calloc<ShaderC>(count),
      castFunc: (ptr) => ptr.cast<ShaderC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<ShaderC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Shader$ = .new(this, r'Ptr$Shader$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<ShaderC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<ShaderC>> at this level',
      valueFunc: Shader$.Value,
      rawArrayFunc: Shader$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Sound$ = .new(this, r'Sound$',
      allocatorFunc: ([count = 1]) => calloc<SoundC>(count),
      castFunc: (ptr) => ptr.cast<SoundC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<SoundC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Sound$ = .new(this, r'Ptr$Sound$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<SoundC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<SoundC>> at this level',
      valueFunc: Sound$.Value,
      rawArrayFunc: Sound$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Texture$ = .new(this, r'Texture$',
      allocatorFunc: ([count = 1]) => calloc<TextureC>(count),
      castFunc: (ptr) => ptr.cast<TextureC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<TextureC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Texture$ = .new(this, r'Ptr$Texture$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<TextureC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<TextureC>> at this level',
      valueFunc: Texture$.Value,
      rawArrayFunc: Texture$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Transform$ = .new(this, r'Transform$',
      allocatorFunc: ([count = 1]) => calloc<TransformC>(count),
      castFunc: (ptr) => ptr.cast<TransformC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<TransformC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Transform$ = .new(this, r'Ptr$Transform$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<TransformC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<TransformC>> at this level',
      valueFunc: Transform$.Value,
      rawArrayFunc: Transform$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Vector2$ = .new(this, r'Vector2$',
      allocatorFunc: ([count = 1]) => calloc<Vector2C>(count),
      castFunc: (ptr) => ptr.cast<Vector2C>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<Vector2C>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Vector2$ = .new(this, r'Ptr$Vector2$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Vector2C>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Vector2C>> at this level',
      valueFunc: Vector2$.Value,
      rawArrayFunc: Vector2$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Vector3$ = .new(this, r'Vector3$',
      allocatorFunc: ([count = 1]) => calloc<Vector3C>(count),
      castFunc: (ptr) => ptr.cast<Vector3C>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<Vector3C>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Vector3$ = .new(this, r'Ptr$Vector3$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Vector3C>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Vector3C>> at this level',
      valueFunc: Vector3$.Value,
      rawArrayFunc: Vector3$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Vector4$ = .new(this, r'Vector4$',
      allocatorFunc: ([count = 1]) => calloc<Vector4C>(count),
      castFunc: (ptr) => ptr.cast<Vector4C>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<Vector4C>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Vector4$ = .new(this, r'Ptr$Vector4$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<Vector4C>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<Vector4C>> at this level',
      valueFunc: Vector4$.Value,
      rawArrayFunc: Vector4$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    VrDeviceInfo$ = .new(this, r'VrDeviceInfo$',
      allocatorFunc: ([count = 1]) => calloc<VrDeviceInfoC>(count),
      castFunc: (ptr) => ptr.cast<VrDeviceInfoC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<VrDeviceInfoC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$VrDeviceInfo$ = .new(this, r'Ptr$VrDeviceInfo$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<VrDeviceInfoC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<VrDeviceInfoC>> at this level',
      valueFunc: VrDeviceInfo$.Value,
      rawArrayFunc: VrDeviceInfo$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    VrStereoConfig$ = .new(this, r'VrStereoConfig$',
      allocatorFunc: ([count = 1]) => calloc<VrStereoConfigC>(count),
      castFunc: (ptr) => ptr.cast<VrStereoConfigC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<VrStereoConfigC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$VrStereoConfig$ = .new(this, r'Ptr$VrStereoConfig$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<VrStereoConfigC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<VrStereoConfigC>> at this level',
      valueFunc: VrStereoConfig$.Value,
      rawArrayFunc: VrStereoConfig$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    Wave$ = .new(this, r'Wave$',
      allocatorFunc: ([count = 1]) => calloc<WaveC>(count),
      castFunc: (ptr) => ptr.cast<WaveC>(),
      printerFunc: (ptr) => ptr.toD().signature(),
      sizeOfFunc: () => sizeOf<WaveC>(),
      indexerFunc: (ptr, i) => ptr[i],
      writeIntoIndexedFunc: (ptr, i, v) => v.writeInto((ptr + i).ref),
      writeIntoFunc: (ptr, v) => v.writeInto(ptr.ref),
      setCFunc: (ptr, i, v) => ptr[i].setC(v),
      indexSetterFunc: (ptr, i, v) => ptr[i] = v,
    );

    Ptr$Wave$ = .new(this, r'Ptr$Wave$',
      allocatorFunc: ([count = 1]) => calloc<Pointer<WaveC>>(count),
      printerFunc: (ptr) => 'We can\'t print Pointer<Pointer<WaveC>> at this level',
      valueFunc: Wave$.Value,
      rawArrayFunc: Wave$.RawArray,
      indexSetterFunc: (ptr, i, value) => ptr[i] = value,
    );

    _allocators = {
      String$.name: String$,
      
      Bool$.name: Bool$,
      Ptr$Bool$.name: Ptr$Bool$,
      Float$.name: Float$,
      Ptr$Float$.name: Ptr$Float$,
      Int$.name: Int$,
      Ptr$Int$.name: Ptr$Int$,
      UInt$.name: UInt$,
      Ptr$UInt$.name: Ptr$UInt$,
      Int8$.name: Int8$,
      Ptr$Int8$.name: Ptr$Int8$,
      UInt8$.name: UInt8$,
      Ptr$UInt8$.name: Ptr$UInt8$,
      Int16$.name: Int16$,
      Ptr$Int16$.name: Ptr$Int16$,
      UInt16$.name: UInt16$,
      Ptr$UInt16$.name: Ptr$UInt16$,
      Int32$.name: Int32$,
      Ptr$Int32$.name: Ptr$Int32$,
      UInt32$.name: UInt32$,
      Ptr$UInt32$.name: Ptr$UInt32$,
      Int64$.name: Int64$,
      Ptr$Int64$.name: Ptr$Int64$,
      UInt64$.name: UInt64$,
      Ptr$UInt64$.name: Ptr$UInt64$,
      Char$.name: Char$,
      Ptr$Char$.name: Ptr$Char$,
      UChar$.name: UChar$,
      Ptr$UChar$.name: Ptr$UChar$,
      UShort$.name: UShort$,
      Ptr$UShort$.name: Ptr$UShort$,
      Short$.name: Short$,
      Ptr$Short$.name: Ptr$Short$,
      AutomationEventList$.name: AutomationEventList$,
      Ptr$AutomationEventList$.name: Ptr$AutomationEventList$,
      AutomationEvent$.name: AutomationEvent$,
      Ptr$AutomationEvent$.name: Ptr$AutomationEvent$,
      AudioStream$.name: AudioStream$,
      Ptr$AudioStream$.name: Ptr$AudioStream$,
      BoneInfo$.name: BoneInfo$,
      Ptr$BoneInfo$.name: Ptr$BoneInfo$,
      BoundingBox$.name: BoundingBox$,
      Ptr$BoundingBox$.name: Ptr$BoundingBox$,
      Camera2D$.name: Camera2D$,
      Ptr$Camera2D$.name: Ptr$Camera2D$,
      Camera3D$.name: Camera3D$,
      Ptr$Camera3D$.name: Ptr$Camera3D$,
      Color$.name: Color$,
      Ptr$Color$.name: Ptr$Color$,
      FilePathList$.name: FilePathList$,
      Ptr$FilePathList$.name: Ptr$FilePathList$,
      Font$.name: Font$,
      Ptr$Font$.name: Ptr$Font$,
      GlyphInfo$.name: GlyphInfo$,
      Ptr$GlyphInfo$.name: Ptr$GlyphInfo$,
      Image$.name: Image$,
      Ptr$Image$.name: Ptr$Image$,
      Light$.name: Light$,
      Ptr$Light$.name: Ptr$Light$,
      Material$.name: Material$,
      Ptr$Material$.name: Ptr$Material$,
      MaterialMap$.name: MaterialMap$,
      Ptr$MaterialMap$.name: Ptr$MaterialMap$,
      Matrix$.name: Matrix$,
      Ptr$Matrix$.name: Ptr$Matrix$,
      Mesh$.name: Mesh$,
      Ptr$Mesh$.name: Ptr$Mesh$,
      Model$.name: Model$,
      Ptr$Model$.name: Ptr$Model$,
      ModelAnimation$.name: ModelAnimation$,
      Ptr$ModelAnimation$.name: Ptr$ModelAnimation$,
      Music$.name: Music$,
      Ptr$Music$.name: Ptr$Music$,
      NPatchInfo$.name: NPatchInfo$,
      Ptr$NPatchInfo$.name: Ptr$NPatchInfo$,
      Rectangle$.name: Rectangle$,
      Ptr$Rectangle$.name: Ptr$Rectangle$,
      RlDrawCall$.name: RlDrawCall$,
      Ptr$RlDrawCall$.name: Ptr$RlDrawCall$,
      RlRenderBatch$.name: RlRenderBatch$,
      Ptr$RlRenderBatch$.name: Ptr$RlRenderBatch$,
      RlVertexBuffer$.name: RlVertexBuffer$,
      Ptr$RlVertexBuffer$.name: Ptr$RlVertexBuffer$,
      Ray$.name: Ray$,
      Ptr$Ray$.name: Ptr$Ray$,
      RayCollision$.name: RayCollision$,
      Ptr$RayCollision$.name: Ptr$RayCollision$,
      RenderTexture$.name: RenderTexture$,
      Ptr$RenderTexture$.name: Ptr$RenderTexture$,
      Shader$.name: Shader$,
      Ptr$Shader$.name: Ptr$Shader$,
      Sound$.name: Sound$,
      Ptr$Sound$.name: Ptr$Sound$,
      Texture$.name: Texture$,
      Ptr$Texture$.name: Ptr$Texture$,
      Transform$.name: Transform$,
      Ptr$Transform$.name: Ptr$Transform$,
      Vector2$.name: Vector2$,
      Ptr$Vector2$.name: Ptr$Vector2$,
      Vector3$.name: Vector3$,
      Ptr$Vector3$.name: Ptr$Vector3$,
      Vector4$.name: Vector4$,
      Ptr$Vector4$.name: Ptr$Vector4$,
      VrDeviceInfo$.name: VrDeviceInfo$,
      Ptr$VrDeviceInfo$.name: Ptr$VrDeviceInfo$,
      VrStereoConfig$.name: VrStereoConfig$,
      Ptr$VrStereoConfig$.name: Ptr$VrStereoConfig$,
      Wave$.name: Wave$,
      Ptr$Wave$.name: Ptr$Wave$,
    };
  }

  Pointer<Char> str(String text) => String$.Value(text);
  Pointer<Char> strAt(String key, [String? text]) => String$.ValueAt(key, text);

  @override
  void dispose() {
    super.dispose();

    debugFreeInfo('Freeing preallocated internals');
    _dePreAllocate();
    
    debugFreeInfo('Freeing preallocated reusable internals');
    _dePreAllocateReusables();

    debugFreeInfo('Freeing ${_allocators.length} built-in allocators');
    _allocators.values.forEach((a) => a._dispose());

    if (_customAllocators.isNotEmpty) {
      debugFreeInfo('Freeing ${_customAllocators.length} custom allocators');
      _customAllocators.values.forEach((a) => a._dispose());
    }
  }

  /// ======================================
  /// ====== PRE-ALLOCATED IMMUTABLES ======
  /// ======================================
  /// 1x  Vector2 => 1 * ( 2*float) => 1 * ( 2*4) =>  8 Bytes
  /// 1x  Vector3 => 1 * ( 3*float) => 1 * ( 3*4) => 12 Bytes
  /// 1x  Vector4 => 1 * ( 4*float) => 1 * ( 4*4) => 16 Bytes
  /// 2x   Matrix => 2 * (16*float) => 2 * (16*4) => 128 Bytes
  /// 1x     Quat => 1 * ( 4*float) => 1 * ( 4*4) => 16 Bytes
  /// ====================================
  /// Total preallocated memory: 180 Bytes
  /// 
  /// NOTE: We do not use slots to not make logs look suspicious
  /// NOTE: Pointers are private, because 'immutables' are meant to be immutable
  ///       (though you can mutate the references)
  
  late Pointer<Vector2C> _vec2ZeroPtr;
  Vector2C get vec2Zero => _vec2ZeroPtr.ref;

  late Pointer<Vector3C> _vec3ZeroPtr;
  Vector3C get vec3Zero => _vec3ZeroPtr.ref;
  
  late Pointer<Vector4C> _vec4ZeroPtr;
  Vector4C get vec4Zero => _vec4ZeroPtr.ref;
  
  late Pointer<MatrixC> _matZeroPtr;
  MatrixC get matZero => _matZeroPtr.ref;
  
  late Pointer<MatrixC> _matIdentityPtr;
  MatrixC get matIdentity => _matIdentityPtr.ref;
  
  late Pointer<QuaternionC> _quatIdentityPtr;
  QuaternionC get quatIdentity => _quatIdentityPtr.ref;

  void _preAllocate() {
    _vec2ZeroPtr = calloc<Vector2C>();
    _vec3ZeroPtr = calloc<Vector3C>();
    _vec4ZeroPtr = calloc<Vector4C>();
    _matZeroPtr = calloc<MatrixC>();
    _matIdentityPtr = calloc<MatrixC>().setD(.identity());
    _quatIdentityPtr = calloc<QuaternionC>().setD(.qIdentity());
  }

  void _dePreAllocate() {
    calloc.free(_vec2ZeroPtr);
    calloc.free(_vec3ZeroPtr);
    calloc.free(_vec4ZeroPtr);
    calloc.free(_matZeroPtr);
    calloc.free(_matIdentityPtr);
  }

  /// =====================================
  /// ====== PRE-ALLOCATED REUSABLES ======
  /// =====================================
  /// 4x   Vector2 => 4 * (2*float)         => 4 * (2*4) => 32 Bytes
  /// 4x   Vector3 => 4 * (3*float)         => 4 * (3*4) => 48 Bytes
  /// 4x   Vector4 => 4 * (4*float)         => 4 * (4*4) => 64 Bytes
  /// 4x     Color => 4 * (4*unsigned char) => 4 * (4*1) => 16 Bytes
  /// 4x Rectangle => 4 * (4*float)         => 4 * (4*4) => 64 Bytes
  /// ====================================
  /// Total preallocated memory: 224 Bytes
  /// 
  /// NOTE: We do not use slots to not make logs look suspicious

  /// Vector2
  
  late Pointer<Vector2C> vec21Ptr;
  Vector2C vec21([num? x, num? y])
    => vec21Ptr.set(x ?? vec21Ptr.ref.x, y ?? vec21Ptr.ref.y).ref;
  Vector2C vec21C(Vector2C o) => vec21(o.x, o.y);
  Vector2C vec21D(Vector2D o) => vec21(o.x, o.y);

  late Pointer<Vector2C> vec22Ptr;
  Vector2C vec22([num? x, num? y])
    => vec22Ptr.set(x ?? vec22Ptr.ref.x, y ?? vec22Ptr.ref.y).ref;
  Vector2C vec22C(Vector2C o) => vec22(o.x, o.y);
  Vector2C vec22D(Vector2D o) => vec22(o.x, o.y);

  late Pointer<Vector2C> vec23Ptr;
  Vector2C vec23([num? x, num? y])
    => vec23Ptr.set(x ?? vec23Ptr.ref.x, y ?? vec23Ptr.ref.y).ref;
  Vector2C vec23C(Vector2C o) => vec23(o.x, o.y);
  Vector2C vec23D(Vector2D o) => vec23(o.x, o.y);

  late Pointer<Vector2C> vec24Ptr;
  Vector2C vec24([num? x, num? y])
    => vec24Ptr.set(x ?? vec24Ptr.ref.x, y ?? vec24Ptr.ref.y).ref;
  Vector2C vec24C(Vector2C o) => vec24(o.x, o.y);
  Vector2C vec24D(Vector2D o) => vec24(o.x, o.y);

  /// Vector3

  late Pointer<Vector3C> vec31Ptr;
  Vector3C vec31([num? x, num? y, num? z])
    => vec31Ptr.set(x ?? vec31Ptr.ref.x, y ?? vec31Ptr.ref.y, z ?? vec31Ptr.ref.z).ref;
  Vector3C vec31C(Vector3C o) => vec31(o.x, o.y, o.z);
  Vector3C vec31D(Vector3D o) => vec31(o.x, o.y, o.z);
    
  late Pointer<Vector3C> vec32Ptr;
  Vector3C vec32([num? x, num? y, num? z])
    => vec32Ptr.set(x ?? vec32Ptr.ref.x, y ?? vec32Ptr.ref.y, z ?? vec32Ptr.ref.z).ref;
  Vector3C vec32C(Vector3C o) => vec32(o.x, o.y, o.z);
  Vector3C vec32D(Vector3D o) => vec32(o.x, o.y, o.z);

  late Pointer<Vector3C> vec33Ptr;
  Vector3C vec33([num? x, num? y, num? z])
    => vec33Ptr.set(x ?? vec33Ptr.ref.x, y ?? vec33Ptr.ref.y, z ?? vec33Ptr.ref.z).ref;
  Vector3C vec33C(Vector3C o) => vec33(o.x, o.y, o.z);
  Vector3C vec33D(Vector3D o) => vec33(o.x, o.y, o.z);

  late Pointer<Vector3C> vec34Ptr;
  Vector3C vec34([num? x, num? y, num? z])
    => vec34Ptr.set(x ?? vec34Ptr.ref.x, y ?? vec34Ptr.ref.y, z ?? vec34Ptr.ref.z).ref;
  Vector3C vec34C(Vector3C o) => vec34(o.x, o.y, o.z);
  Vector3C vec34D(Vector3D o) => vec34(o.x, o.y, o.z);

  /// Vector4

  late Pointer<Vector4C> vec41Ptr;
  Vector4C vec41([num? x, num? y, num? z, num? w])
    => vec41Ptr.set(x ?? vec41Ptr.ref.x, y ?? vec41Ptr.ref.y, z ?? vec41Ptr.ref.z, w ?? vec41Ptr.ref.w).ref;
  Vector4C vec41C(Vector4C o) => vec41(o.x, o.y, o.z);
  Vector4C vec41D(Vector4D o) => vec41(o.x, o.y, o.z);
    
  late Pointer<Vector4C> vec42Ptr;
  Vector4C vec42([num? x, num? y, num? z, num? w])
    => vec42Ptr.set(x ?? vec42Ptr.ref.x, y ?? vec42Ptr.ref.y, z ?? vec42Ptr.ref.z, w ?? vec42Ptr.ref.w).ref;
  Vector4C vec42C(Vector4C o) => vec42(o.x, o.y, o.z);
  Vector4C vec42D(Vector4D o) => vec42(o.x, o.y, o.z);

  late Pointer<Vector4C> vec43Ptr;
  Vector4C vec43([num? x, num? y, num? z, num? w])
    => vec43Ptr.set(x ?? vec43Ptr.ref.x, y ?? vec43Ptr.ref.y, z ?? vec43Ptr.ref.z, w ?? vec43Ptr.ref.w).ref;
  Vector4C vec43C(Vector4C o) => vec43(o.x, o.y, o.z);
  Vector4C vec43D(Vector4D o) => vec43(o.x, o.y, o.z);

  late Pointer<Vector4C> vec44Ptr;
  Vector4C vec44([num? x, num? y, num? z, num? w])
    => vec44Ptr.set(x ?? vec44Ptr.ref.x, y ?? vec44Ptr.ref.y, z ?? vec44Ptr.ref.z, w ?? vec44Ptr.ref.w).ref;
  Vector4C vec44C(Vector4C o) => vec44(o.x, o.y, o.z);
  Vector4C vec44D(Vector4D o) => vec44(o.x, o.y, o.z);

  /// Color

  late Pointer<ColorC> color1Ptr;
  ColorC color1([num? r, num? g, num? b, num? a])
    => color1Ptr.set(r ?? color1Ptr.ref.r, g ?? color1Ptr.ref.g, b ?? color1Ptr.ref.b, a ?? color1Ptr.ref.a).ref;
  ColorC color1C(ColorC o) => color1(o.r, o.g, o.b, o.a);
  ColorC color1D(ColorD o) => color1(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color2Ptr;
  ColorC color2([num? r, num? g, num? b, num? a])
    => color2Ptr.set(r ?? color2Ptr.ref.r, g ?? color2Ptr.ref.g, b ?? color2Ptr.ref.b, a ?? color2Ptr.ref.a).ref;
  ColorC color2C(ColorC o) => color2(o.r, o.g, o.b, o.a);
  ColorC color2D(ColorD o) => color2(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color3Ptr;
  ColorC color3([num? r, num? g, num? b, num? a])
    => color3Ptr.set(r ?? color3Ptr.ref.r, g ?? color3Ptr.ref.g, b ?? color3Ptr.ref.b, a ?? color3Ptr.ref.a).ref;
  ColorC color3C(ColorC o) => color3(o.r, o.g, o.b, o.a);
  ColorC color3D(ColorD o) => color3(o.r, o.g, o.b, o.a);

  late Pointer<ColorC> color4Ptr;
  ColorC color4([num? r, num? g, num? b, num? a])
    => color4Ptr.set(r ?? color4Ptr.ref.r, g ?? color4Ptr.ref.g, b ?? color4Ptr.ref.b, a ?? color4Ptr.ref.a).ref;
  ColorC color4C(ColorC o) => color4(o.r, o.g, o.b, o.a);
  ColorC color4D(ColorD o) => color4(o.r, o.g, o.b, o.a);

  /// Rectangle

  late Pointer<RectangleC> rect1Ptr;
  RectangleC rect1([num? x, num? y, num? w, num? h])
    => rect1Ptr.set(x ?? rect1Ptr.ref.x, y ?? rect1Ptr.ref.y, w ?? rect1Ptr.ref.width, h ?? rect1Ptr.ref.height).ref;
  RectangleC rect1C(RectangleC o) => rect1(o.x, o.y, o.width, o.height);
  RectangleC rect1D(RectangleD o) => rect1(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect2Ptr;
  RectangleC rect2([num? x, num? y, num? w, num? h])
    => rect2Ptr.set(x ?? rect2Ptr.ref.x, y ?? rect2Ptr.ref.y, w ?? rect2Ptr.ref.width, h ?? rect2Ptr.ref.height).ref;
  RectangleC rect2C(RectangleC o) => rect2(o.x, o.y, o.width, o.height);
  RectangleC rect2D(RectangleD o) => rect2(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect3Ptr;
  RectangleC rect3([num? x, num? y, num? w, num? h])
    => rect3Ptr.set(x ?? rect3Ptr.ref.x, y ?? rect3Ptr.ref.y, w ?? rect3Ptr.ref.width, h ?? rect3Ptr.ref.height).ref;
  RectangleC rect3C(RectangleC o) => rect3(o.x, o.y, o.width, o.height);
  RectangleC rect3D(RectangleD o) => rect3(o.x, o.y, o.width, o.height);

  late Pointer<RectangleC> rect4Ptr;
  RectangleC rect4([num? x, num? y, num? w, num? h])
    => rect4Ptr.set(x ?? rect4Ptr.ref.x, y ?? rect4Ptr.ref.y, w ?? rect4Ptr.ref.width, h ?? rect4Ptr.ref.height).ref;
  RectangleC rect4C(RectangleC o) => rect4(o.x, o.y, o.width, o.height);
  RectangleC rect4D(RectangleD o) => rect4(o.x, o.y, o.width, o.height);

  void _preAllocateReusables() {
    vec21Ptr = calloc<Vector2C>();
    vec22Ptr = calloc<Vector2C>();
    vec23Ptr = calloc<Vector2C>();
    vec24Ptr = calloc<Vector2C>();

    vec31Ptr = calloc<Vector3C>();
    vec32Ptr = calloc<Vector3C>();
    vec33Ptr = calloc<Vector3C>();
    vec34Ptr = calloc<Vector3C>();
    
    vec41Ptr = calloc<Vector4C>();
    vec42Ptr = calloc<Vector4C>();
    vec43Ptr = calloc<Vector4C>();
    vec44Ptr = calloc<Vector4C>();
    
    color1Ptr = calloc<ColorC>();
    color2Ptr = calloc<ColorC>();
    color3Ptr = calloc<ColorC>();
    color4Ptr = calloc<ColorC>();
    
    rect1Ptr = calloc<RectangleC>();
    rect2Ptr = calloc<RectangleC>();
    rect3Ptr = calloc<RectangleC>();
    rect4Ptr = calloc<RectangleC>();
  }

  void _dePreAllocateReusables() {
    calloc.free(vec21Ptr);
    calloc.free(vec22Ptr);
    calloc.free(vec23Ptr);
    calloc.free(vec24Ptr);

    calloc.free(vec31Ptr);
    calloc.free(vec32Ptr);
    calloc.free(vec33Ptr);
    calloc.free(vec34Ptr);
    
    calloc.free(vec41Ptr);
    calloc.free(vec42Ptr);
    calloc.free(vec43Ptr);
    calloc.free(vec44Ptr);
    
    calloc.free(color1Ptr);
    calloc.free(color2Ptr);
    calloc.free(color3Ptr);
    calloc.free(color4Ptr);

    calloc.free(rect1Ptr);
    calloc.free(rect2Ptr);
    calloc.free(rect3Ptr);
    calloc.free(rect4Ptr);
  }
}