part of '../../../raylib.dart';

enum RlDrawMode {
  RL_LINES(0x0001),
  RL_TRIANGLES(0x0004),
  RL_QUADS(0x0007);

  final int value;
  const RlDrawMode(this.value);

  static RlDrawMode fromValue(int value) => switch (value) {
    0x0001 => RL_LINES,
    0x0004 => RL_TRIANGLES,
    0x0007 => RL_QUADS,
    _ => throw ArgumentError('Unknown value for rlDrawMode: $value'),
  };
}

enum RlShaderType {
  RL_FRAGMENT_SHADER(0x8B30),
  RL_VERTEX_SHADER(0x8B31),
  RL_COMPUTE_SHADER(0x91B9);

  final int value;
  const RlShaderType(this.value);

  static RlShaderType fromValue(int value) => switch (value) {
    0x8B30 => RL_FRAGMENT_SHADER,
    0x8B31 => RL_VERTEX_SHADER,
    0x91B9 => RL_COMPUTE_SHADER,
    _ => throw ArgumentError('Unknown value for rlShaderType: $value'),
  };
}

enum RlUsageHint {
  RL_STREAM_DRAW(0x88E0),
  RL_STREAM_READ(0x88E1),
  RL_STREAM_COPY(0x88E2),
  RL_STATIC_DRAW(0x88E4),
  RL_STATIC_READ(0x88E5),
  RL_STATIC_COPY(0x88E6),
  RL_DYNAMIC_DRAW(0x88E8),
  RL_DYNAMIC_READ(0x88E9),
  RL_DYNAMIC_COPY(0x88EA);

  final int value;
  const RlUsageHint(this.value);

  static RlUsageHint fromValue(int value) => switch (value) {
    0x88E0 => RL_STREAM_DRAW,
    0x88E1 => RL_STREAM_READ,
    0x88E2 => RL_STREAM_COPY,
    0x88E4 => RL_STATIC_DRAW,
    0x88E5 => RL_STATIC_READ,
    0x88E6 => RL_STATIC_COPY,
    0x88E8 => RL_DYNAMIC_DRAW,
    0x88E9 => RL_DYNAMIC_READ,
    0x88EA => RL_DYNAMIC_COPY,
    _ => throw ArgumentError('Unknown value for rlUsageHint: $value'),
  };
}

enum RlMatrixMode {
  RL_MODELVIEW(0x1700),
  RL_PROJECTION(0x1701),
  RL_TEXTURE(0x1702);

  final int value;
  const RlMatrixMode(this.value);

  static RlMatrixMode fromValue(int value) => switch (value) {
    0x1700 => RL_MODELVIEW,
    0x1701 => RL_PROJECTION,
    0x1702 => RL_TEXTURE,
    _ => throw ArgumentError('Unknown value for rlMatrixMode: $value'),
  };
}

enum RlGlVersion {
  RL_OPENGL_11(1),
  RL_OPENGL_21(2),
  RL_OPENGL_33(3),
  RL_OPENGL_43(4),
  RL_OPENGL_ES_20(5),
  RL_OPENGL_ES_30(6);

  final int value;
  const RlGlVersion(this.value);

  static RlGlVersion fromValue(int value) => switch (value) {
    1 => RL_OPENGL_11,
    2 => RL_OPENGL_21,
    3 => RL_OPENGL_33,
    4 => RL_OPENGL_43,
    5 => RL_OPENGL_ES_20,
    6 => RL_OPENGL_ES_30,
    _ => throw ArgumentError('Unknown value for rlGlVersion: $value'),
  };
}

enum RlTraceLogLevel {
  RL_LOG_ALL(0),
  RL_LOG_TRACE(1),
  RL_LOG_DEBUG(2),
  RL_LOG_INFO(3),
  RL_LOG_WARNING(4),
  RL_LOG_ERROR(5),
  RL_LOG_FATAL(6),
  RL_LOG_NONE(7);

  final int value;
  const RlTraceLogLevel(this.value);

  static RlTraceLogLevel fromValue(int value) => switch (value) {
    0 => RL_LOG_ALL,
    1 => RL_LOG_TRACE,
    2 => RL_LOG_DEBUG,
    3 => RL_LOG_INFO,
    4 => RL_LOG_WARNING,
    5 => RL_LOG_ERROR,
    6 => RL_LOG_FATAL,
    7 => RL_LOG_NONE,
    _ => throw ArgumentError('Unknown value for rlTraceLogLevel: $value'),
  };
}

enum RlPixelFormat with FEnum {
  RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE(1),
  RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA(2),
  RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5(3),
  RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8(4),
  RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1(5),
  RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4(6),
  RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8(7),
  RL_PIXELFORMAT_UNCOMPRESSED_R32(8),
  RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32(9),
  RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32(10),
  RL_PIXELFORMAT_UNCOMPRESSED_R16(11),
  RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16(12),
  RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16(13),
  RL_PIXELFORMAT_COMPRESSED_DXT1_RGB(14),
  RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA(15),
  RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA(16),
  RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA(17),
  RL_PIXELFORMAT_COMPRESSED_ETC1_RGB(18),
  RL_PIXELFORMAT_COMPRESSED_ETC2_RGB(19),
  RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA(20),
  RL_PIXELFORMAT_COMPRESSED_PVRT_RGB(21),
  RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA(22),
  RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA(23),
  RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA(24);

  const RlPixelFormat(this.value);

  @override
  final int value;

  static RlPixelFormat fromValue(int value) => switch (value) {
    1 => RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE,
    2 => RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA,
    3 => RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5,
    4 => RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8,
    5 => RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1,
    6 => RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4,
    7 => RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
    8 => RL_PIXELFORMAT_UNCOMPRESSED_R32,
    9 => RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32,
    10 => RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32,
    11 => RL_PIXELFORMAT_UNCOMPRESSED_R16,
    12 => RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16,
    13 => RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16,
    14 => RL_PIXELFORMAT_COMPRESSED_DXT1_RGB,
    15 => RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA,
    16 => RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA,
    17 => RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA,
    18 => RL_PIXELFORMAT_COMPRESSED_ETC1_RGB,
    19 => RL_PIXELFORMAT_COMPRESSED_ETC2_RGB,
    20 => RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA,
    21 => RL_PIXELFORMAT_COMPRESSED_PVRT_RGB,
    22 => RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA,
    23 => RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA,
    24 => RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA,
    _ => throw ArgumentError('Unknown value for rlPixelFormat: $value'),
  };
}

enum RlTextureFilter {
  RL_TEXTURE_FILTER_POINT(0),
  RL_TEXTURE_FILTER_BILINEAR(1),
  RL_TEXTURE_FILTER_TRILINEAR(2),
  RL_TEXTURE_FILTER_ANISOTROPIC_4X(3),
  RL_TEXTURE_FILTER_ANISOTROPIC_8X(4),
  RL_TEXTURE_FILTER_ANISOTROPIC_16X(5);

  final int value;
  const RlTextureFilter(this.value);

  static RlTextureFilter fromValue(int value) => switch (value) {
    0 => RL_TEXTURE_FILTER_POINT,
    1 => RL_TEXTURE_FILTER_BILINEAR,
    2 => RL_TEXTURE_FILTER_TRILINEAR,
    3 => RL_TEXTURE_FILTER_ANISOTROPIC_4X,
    4 => RL_TEXTURE_FILTER_ANISOTROPIC_8X,
    5 => RL_TEXTURE_FILTER_ANISOTROPIC_16X,
    _ => throw ArgumentError('Unknown value for rlTextureFilter: $value'),
  };
}

enum RlBlendMode {
  RL_BLEND_ALPHA(0),
  RL_BLEND_ADDITIVE(1),
  RL_BLEND_MULTIPLIED(2),
  RL_BLEND_ADD_COLORS(3),
  RL_BLEND_SUBTRACT_COLORS(4),
  RL_BLEND_ALPHA_PREMULTIPLY(5),
  RL_BLEND_CUSTOM(6),
  RL_BLEND_CUSTOM_SEPARATE(7);

  final int value;
  const RlBlendMode(this.value);

  static RlBlendMode fromValue(int value) => switch (value) {
    0 => RL_BLEND_ALPHA,
    1 => RL_BLEND_ADDITIVE,
    2 => RL_BLEND_MULTIPLIED,
    3 => RL_BLEND_ADD_COLORS,
    4 => RL_BLEND_SUBTRACT_COLORS,
    5 => RL_BLEND_ALPHA_PREMULTIPLY,
    6 => RL_BLEND_CUSTOM,
    7 => RL_BLEND_CUSTOM_SEPARATE,
    _ => throw ArgumentError('Unknown value for rlBlendMode: $value'),
  };
}

enum RlShaderLocationIndex {
  RL_SHADER_LOC_VERTEX_POSITION(0),
  RL_SHADER_LOC_VERTEX_TEXCOORD01(1),
  RL_SHADER_LOC_VERTEX_TEXCOORD02(2),
  RL_SHADER_LOC_VERTEX_NORMAL(3),
  RL_SHADER_LOC_VERTEX_TANGENT(4),
  RL_SHADER_LOC_VERTEX_COLOR(5),
  RL_SHADER_LOC_MATRIX_MVP(6),
  RL_SHADER_LOC_MATRIX_VIEW(7),
  RL_SHADER_LOC_MATRIX_PROJECTION(8),
  RL_SHADER_LOC_MATRIX_MODEL(9),
  RL_SHADER_LOC_MATRIX_NORMAL(10),
  RL_SHADER_LOC_VECTOR_VIEW(11),
  RL_SHADER_LOC_COLOR_DIFFUSE(12),
  RL_SHADER_LOC_COLOR_SPECULAR(13),
  RL_SHADER_LOC_COLOR_AMBIENT(14),
  RL_SHADER_LOC_MAP_ALBEDO(15),
  RL_SHADER_LOC_MAP_METALNESS(16),
  RL_SHADER_LOC_MAP_NORMAL(17),
  RL_SHADER_LOC_MAP_ROUGHNESS(18),
  RL_SHADER_LOC_MAP_OCCLUSION(19),
  RL_SHADER_LOC_MAP_EMISSION(20),
  RL_SHADER_LOC_MAP_HEIGHT(21),
  RL_SHADER_LOC_MAP_CUBEMAP(22),
  RL_SHADER_LOC_MAP_IRRADIANCE(23),
  RL_SHADER_LOC_MAP_PREFILTER(24),
  RL_SHADER_LOC_MAP_BRDF(25);

  final int value;
  const RlShaderLocationIndex(this.value);

  static RlShaderLocationIndex fromValue(int value) => switch (value) {
    0 => RL_SHADER_LOC_VERTEX_POSITION,
    1 => RL_SHADER_LOC_VERTEX_TEXCOORD01,
    2 => RL_SHADER_LOC_VERTEX_TEXCOORD02,
    3 => RL_SHADER_LOC_VERTEX_NORMAL,
    4 => RL_SHADER_LOC_VERTEX_TANGENT,
    5 => RL_SHADER_LOC_VERTEX_COLOR,
    6 => RL_SHADER_LOC_MATRIX_MVP,
    7 => RL_SHADER_LOC_MATRIX_VIEW,
    8 => RL_SHADER_LOC_MATRIX_PROJECTION,
    9 => RL_SHADER_LOC_MATRIX_MODEL,
    10 => RL_SHADER_LOC_MATRIX_NORMAL,
    11 => RL_SHADER_LOC_VECTOR_VIEW,
    12 => RL_SHADER_LOC_COLOR_DIFFUSE,
    13 => RL_SHADER_LOC_COLOR_SPECULAR,
    14 => RL_SHADER_LOC_COLOR_AMBIENT,
    15 => RL_SHADER_LOC_MAP_ALBEDO,
    16 => RL_SHADER_LOC_MAP_METALNESS,
    17 => RL_SHADER_LOC_MAP_NORMAL,
    18 => RL_SHADER_LOC_MAP_ROUGHNESS,
    19 => RL_SHADER_LOC_MAP_OCCLUSION,
    20 => RL_SHADER_LOC_MAP_EMISSION,
    21 => RL_SHADER_LOC_MAP_HEIGHT,
    22 => RL_SHADER_LOC_MAP_CUBEMAP,
    23 => RL_SHADER_LOC_MAP_IRRADIANCE,
    24 => RL_SHADER_LOC_MAP_PREFILTER,
    25 => RL_SHADER_LOC_MAP_BRDF,
    _ => throw ArgumentError('Unknown value for rlShaderLocationIndex: $value'),
  };
}

enum RlShaderUniformDataType {
  RL_SHADER_UNIFORM_FLOAT(0),
  RL_SHADER_UNIFORM_VEC2(1),
  RL_SHADER_UNIFORM_VEC3(2),
  RL_SHADER_UNIFORM_VEC4(3),
  RL_SHADER_UNIFORM_INT(4),
  RL_SHADER_UNIFORM_IVEC2(5),
  RL_SHADER_UNIFORM_IVEC3(6),
  RL_SHADER_UNIFORM_IVEC4(7),
  RL_SHADER_UNIFORM_UINT(8),
  RL_SHADER_UNIFORM_UIVEC2(9),
  RL_SHADER_UNIFORM_UIVEC3(10),
  RL_SHADER_UNIFORM_UIVEC4(11),
  RL_SHADER_UNIFORM_SAMPLER2D(12);

  final int value;
  const RlShaderUniformDataType(this.value);

  static RlShaderUniformDataType fromValue(int value) => switch (value) {
    0 => RL_SHADER_UNIFORM_FLOAT,
    1 => RL_SHADER_UNIFORM_VEC2,
    2 => RL_SHADER_UNIFORM_VEC3,
    3 => RL_SHADER_UNIFORM_VEC4,
    4 => RL_SHADER_UNIFORM_INT,
    5 => RL_SHADER_UNIFORM_IVEC2,
    6 => RL_SHADER_UNIFORM_IVEC3,
    7 => RL_SHADER_UNIFORM_IVEC4,
    8 => RL_SHADER_UNIFORM_UINT,
    9 => RL_SHADER_UNIFORM_UIVEC2,
    10 => RL_SHADER_UNIFORM_UIVEC3,
    11 => RL_SHADER_UNIFORM_UIVEC4,
    12 => RL_SHADER_UNIFORM_SAMPLER2D,
    _ => throw ArgumentError(
      'Unknown value for rlShaderUniformDataType: $value',
    ),
  };
}

enum RlShaderAttributeDataType {
  RL_SHADER_ATTRIB_FLOAT(0),
  RL_SHADER_ATTRIB_VEC2(1),
  RL_SHADER_ATTRIB_VEC3(2),
  RL_SHADER_ATTRIB_VEC4(3);

  final int value;
  const RlShaderAttributeDataType(this.value);

  static RlShaderAttributeDataType fromValue(int value) => switch (value) {
    0 => RL_SHADER_ATTRIB_FLOAT,
    1 => RL_SHADER_ATTRIB_VEC2,
    2 => RL_SHADER_ATTRIB_VEC3,
    3 => RL_SHADER_ATTRIB_VEC4,
    _ => throw ArgumentError(
      'Unknown value for rlShaderAttributeDataType: $value',
    ),
  };
}

enum RlFramebufferAttachType {
  RL_ATTACHMENT_COLOR_CHANNEL0(0),
  RL_ATTACHMENT_COLOR_CHANNEL1(1),
  RL_ATTACHMENT_COLOR_CHANNEL2(2),
  RL_ATTACHMENT_COLOR_CHANNEL3(3),
  RL_ATTACHMENT_COLOR_CHANNEL4(4),
  RL_ATTACHMENT_COLOR_CHANNEL5(5),
  RL_ATTACHMENT_COLOR_CHANNEL6(6),
  RL_ATTACHMENT_COLOR_CHANNEL7(7),
  RL_ATTACHMENT_DEPTH(100),
  RL_ATTACHMENT_STENCIL(200);

  final int value;
  const RlFramebufferAttachType(this.value);

  static RlFramebufferAttachType fromValue(int value) => switch (value) {
    0 => RL_ATTACHMENT_COLOR_CHANNEL0,
    1 => RL_ATTACHMENT_COLOR_CHANNEL1,
    2 => RL_ATTACHMENT_COLOR_CHANNEL2,
    3 => RL_ATTACHMENT_COLOR_CHANNEL3,
    4 => RL_ATTACHMENT_COLOR_CHANNEL4,
    5 => RL_ATTACHMENT_COLOR_CHANNEL5,
    6 => RL_ATTACHMENT_COLOR_CHANNEL6,
    7 => RL_ATTACHMENT_COLOR_CHANNEL7,
    100 => RL_ATTACHMENT_DEPTH,
    200 => RL_ATTACHMENT_STENCIL,
    _ => throw ArgumentError(
      'Unknown value for rlFramebufferAttachType: $value',
    ),
  };
}

enum RlFramebufferAttachTextureType {
  RL_ATTACHMENT_CUBEMAP_POSITIVE_X(0),
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_X(1),
  RL_ATTACHMENT_CUBEMAP_POSITIVE_Y(2),
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y(3),
  RL_ATTACHMENT_CUBEMAP_POSITIVE_Z(4),
  RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z(5),
  RL_ATTACHMENT_TEXTURE2D(100),
  RL_ATTACHMENT_RENDERBUFFER(200);

  final int value;
  const RlFramebufferAttachTextureType(this.value);

  static RlFramebufferAttachTextureType fromValue(int value) => switch (value) {
    0 => RL_ATTACHMENT_CUBEMAP_POSITIVE_X,
    1 => RL_ATTACHMENT_CUBEMAP_NEGATIVE_X,
    2 => RL_ATTACHMENT_CUBEMAP_POSITIVE_Y,
    3 => RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y,
    4 => RL_ATTACHMENT_CUBEMAP_POSITIVE_Z,
    5 => RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z,
    100 => RL_ATTACHMENT_TEXTURE2D,
    200 => RL_ATTACHMENT_RENDERBUFFER,
    _ => throw ArgumentError(
      'Unknown value for rlFramebufferAttachTextureType: $value',
    ),
  };
}

enum RlCullMode {
  RL_CULL_FACE_FRONT(0),
  RL_CULL_FACE_BACK(1);

  final int value;
  const RlCullMode(this.value);

  static RlCullMode fromValue(int value) => switch (value) {
    0 => RL_CULL_FACE_FRONT,
    1 => RL_CULL_FACE_BACK,
    _ => throw ArgumentError('Unknown value for rlCullMode: $value'),
  };
}