export '_base.dart';
export '../core/modules/dart/audio/abbr.dart';
export '../core/modules/dart/camera/abbr.dart';
export '../core/modules/dart/core/abbr.dart';
export '../core/modules/dart/gui/abbr.dart';
export '../core/modules/dart/light/abbr.dart';
export '../core/modules/dart/msf_gif/abbr.dart';
export '../core/modules/dart/rlgl/abbr.dart';

export 'package:raylib_dartified_base/abbr.dart';

import 'package:raylib_dartified/raylib_dartified.dart';

ColorD get LIGHTGRAY => .LIGHTGRAY;
ColorD get GRAY => .GRAY;
ColorD get DARKGRAY => .DARKGRAY;
ColorD get YELLOW => .YELLOW;
ColorD get GOLD => .GOLD;
ColorD get ORANGE => .ORANGE;
ColorD get PINK => .PINK;
ColorD get RED => .RED;
ColorD get MAROON => .MAROON;
ColorD get GREEN => .GREEN;
ColorD get LIME => .LIME;
ColorD get DARKGREEN => .DARKGREEN;
ColorD get SKYBLUE => .SKYBLUE;
ColorD get BLUE => .BLUE;
ColorD get DARKBLUE => .DARKBLUE;
ColorD get PURPLE => .PURPLE;
ColorD get VIOLET => .VIOLET;
ColorD get DARKPURPLE => .DARKPURPLE;
ColorD get BEIGE => .BEIGE;
ColorD get BROWN => .BROWN;
ColorD get DARKBROWN => .DARKBROWN;
ColorD get WHITE => .WHITE;
ColorD get BLACK => .BLACK;
ColorD get BLANK => .BLANK;
ColorD get MAGENTA => .MAGENTA;
ColorD get RAYWHITE => .RAYWHITE;
ColorD get TRANSPARENT => .TRANSPARENT;